import { defineContent } from "../types";
export const defaults = {
  f001: "Home",
  f002: "About Us",
  f003: "Ascent Group Construction 5-Step Project Process",
  f004: "Our proven approach to delivering reliable building envelope and restoration projects",
  f005: "About — Envelope & Restoration",
  f006: "15+ years of combined experience in building envelope, restoration & interior trades across the GTA — now operating as Ascent Group Construction.",
  f007: "About Ascent Group",
  f008: "Ascent Group Construction team at work on a building facade",
  f009: "Start a Project",
  f010: "Request Site Assessment",
  f011: "Home",
  f012: "About Us",
  f013: "Story",
  f014: "Our Story",
  f015: "Milestones",
  f016: "Key moments behind Ascent Group's specialty contracting capability.",
  f017: "Years Team Experience",
  f019: "CGL Coverage",
  f020: "WSIB Compliant",
  f021: "Self-Performed",
  f022: "Founder",
  f023: "Founder",
  f024: "Values",
  f025: "What We Stand For",
  f026: "Six principles that guide every project, every interaction, every decision.",
  f027: "Capabilities",
  f028: "What We Self-Perform",
  f029: "Each scope is planned for minimal disruption, clear sequencing, and documented QA/QC.",
  f030: "View All Services",
  f031: "Who We Work With",
  f032: "Built for clients who value reliability, clear communication, and professional trade execution.",
  f033: "Learn more",
  f034: "Our 5-Step Approach",
  f035: "A consistent process for every project — from first call to final closeout.",
  f036: "Full Process Details",
  f037: "Service Areas",
  f038: "Service Area",
  f039: "Where We Work",
  f040: "Primarily serving",
  f041: "Ontario & the Greater Toronto Area",
  f042: ". We consider broader Ontario for the right project.",
  f043: "People Also Ask",
  f044: "Common questions about our company, founder, and approach.",
  f045: "Ascent Group Founded",
  f046: "Established by Hebun Isik after graduating from George Brown College's Construction Engineering Technology program — backed by a crew with 15+ years of combined building envelope and interior trades experience.",
  f047: "Initial Project Portfolio",
  f048: "First projects delivered across the GTA — focused on EIFS, masonry repair, waterproofing, and interior finishes with self-performed crews.",
  f049: "Sto Canada Listed Installer",
  f050: "Listed for Modules SCL-001 through SCL-010, formalizing our EIFS and wall system credentials.",
  f051: "Building Trade Partnerships",
  f052: "Growing relationships with general contractors, property managers, and building consultants throughout Ontario.",
  f053: "Façade Remediation & Cladding",
  f054: "Sealant Replacement Programs",
  f055: "Concrete & Parking Garage Repairs",
  f056: "EIFS & Stucco Systems",
  f057: "Masonry Restoration",
  f058: "Waterproofing Systems",
  f059: "Protective & Architectural Coatings",
  f060: "Flooring & Tile",
  f061: "Residential & Commercial Painting",
  f062: "Interior Buildouts",
  f063: "Professional Execution",
  f064: "We bring the same professional standards developed on major GTA projects to every job, regardless of size.",
  f065: "Clear Accountability",
  f066: "You work directly with the people on your site. No subcontractor layers, no finger-pointing.",
  f067: "Honest Communication",
  f068: "Realistic schedules, detailed scopes, proactive updates. If issues arise, you hear about them immediately with solutions.",
  f069: "Relationship First",
  f070: "Every client relationship matters. We earn trust through consistent, professional work and reliable follow-through.",
  f071: "Safety First",
  f072: "WSIB compliant, proper safety protocols, and the right equipment on every job. We never compromise on safety.",
  f073: "Long-Term Thinking",
  f074: "We're building for the long term — sustainable growth through client satisfaction and a strong market reputation.",
  f075: "General Contractors",
  f076: "Dependable specialty trade partners for envelope, EIFS, masonry, and interior work on commercial and multi-residential projects.",
  f077: "Property Managers",
  f078: "Envelope and interior trades for building maintenance, restoration, and capital projects — with minimal tenant disruption.",
  f079: "Developers & Owners",
  f080: "Direct prime-scope pricing without subcontractor markup layers, backed by proven GTA project experience.",
  f081: "Building Consultants",
  f082: "Reliable contractors who follow your specifications, document everything, and respond professionally to RFIs.",
  f083: "Site Walk & Assessment",
  f084: "We meet on site to understand the issue, constraints, and access. For urgent matters, we aim to attend within 48–72 hours.",
  f085: "Scope & Proposal",
  f086: "You receive a clear, itemized scope — drawings/photos as needed, alternates where helpful, and unit rates for repetitive work. We prioritize fast, complete submittals.",
  f087: "Mobilize & Execute",
  f088: "We coordinate permits, access, logistics, and occupant notices. A dedicated lead oversees daily safety, quality, and schedule.",
  f089: "Quality Assurance & Reporting",
  f090: "Field checks, photo logs, and inspection records ensure work follows specifications and manufacturer guidance.",
  f091: "Closeout & Warranty",
  f092: "Final walkthrough, punch completion, turnover package with photos and product data, and applicable warranty.",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 435,
    locked: false,
  },
  f007: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "Our Story",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f020: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f021: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Founder",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "View All Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Learn more",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "Full Process Details",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Service Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Where We Work",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "Primarily serving",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Ontario & the Greater Toronto Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: ". We consider broader Ontario for the right project.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 630,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 414,
    locked: false,
  },
  f049: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f050: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 333,
    locked: false,
  },
  f053: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 318,
    locked: false,
  },
  f065: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 363,
    locked: false,
  },
  f069: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 345,
    locked: false,
  },
  f071: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 327,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f073: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 339,
    locked: false,
  },
  f075: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f077: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 366,
    locked: false,
  },
  f079: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 312,
    locked: false,
  },
  f081: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 327,
    locked: false,
  },
  f083: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 366,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f085: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 501,
    locked: false,
  },
  f087: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 378,
    locked: false,
  },
  f089: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f090: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 330,
    locked: false,
  },
  f091: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f092: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 324,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("about", defaults, meta);
export const schema = module.schema;
export default module;
