import { defineContent } from "../types";
export const defaults = {
  f001: "Accessibility Statement | Ascent Group Construction",
  f003: "Ascent Group Construction's commitment to web accessibility - WCAG 2.0 Level AA compliance, accessibility features, and how to request assistance.",
  f005: "index, follow",
  f006: "Accessibility Statement",
  f007: "Last Updated: ",
  f008: "Our Commitment to Accessibility",
  f009: "Ascent Group Construction is committed to ensuring digital accessibility for people with disabilities. We continually work to improve the user experience for all visitors and apply relevant accessibility standards to ensure our website is accessible to everyone.",
  f010: "We are committed to complying with the Accessibility for Ontarians with Disabilities Act (AODA) and strive to meet or exceed the Web Content Accessibility Guidelines (WCAG) 2.0 Level AA standards.",
  f011: "Conformance Status",
  f012: "Conformance Level:",
  f013: "WCAG 2.0 Level AA (Partial Conformance)",
  f014: "Partial conformance means that some parts of the content do not fully conform to the accessibility standard. We are actively working to achieve full conformance.",
  f015: "Our website has been designed with accessibility in mind and tested using industry-standard tools and manual testing procedures. We are committed to ongoing improvements and regular accessibility audits.",
  f016: "Accessibility Features",
  f017: "Our website includes the following accessibility features:",
  f018: "Keyboard Navigation",
  f019: "Skip Links:",
  f020: "Skip to main content links on all pages",
  f021: "Logical Tab Order:",
  f022: "Keyboard navigation follows a logical sequence",
  f023: "Focus Indicators:",
  f024: "Clear visual indicators show keyboard focus",
  f025: "No Keyboard Traps:",
  f026: "All interactive elements are keyboard accessible",
  f027: "Screen Reader Support",
  f028: "Semantic HTML:",
  f029: "Proper use of HTML5 semantic elements",
  f030: "ARIA Landmarks:",
  f031: "Page regions identified with ARIA landmarks",
  f032: "ARIA Labels:",
  f033: "Descriptive labels for interactive elements",
  f034: "Alt Text:",
  f035: "Alternative text for all meaningful images",
  f036: "Form Labels:",
  f037: "Clear labels and instructions for all form fields",
  f038: "Visual Accessibility",
  f039: "Color Contrast:",
  f040: "Text meets WCAG AA contrast ratios (4.5:1 for normal text, 3:1 for large text)",
  f041: "Resizable Text:",
  f042: "Text can be resized up to 200% without loss of functionality",
  f043: "Color Independence:",
  f044: "Information is not conveyed by color alone",
  f045: "Responsive Design:",
  f046: "Content adapts to different screen sizes and orientations",
  f047: "Content Structure",
  f048: "Heading Hierarchy:",
  f049: "Proper use of heading levels (H1-H6)",
  f050: "Descriptive Links:",
  f051: "Link text describes the destination or purpose",
  f052: "List Markup:",
  f053: "Lists are properly marked up with semantic HTML",
  f054: "Table Headers:",
  f055: "Data tables include proper header associations",
  f056: "Media and Content",
  f057: "Video Captions:",
  f058: "Videos include captions where applicable",
  f059: "Reduced Motion:",
  f060: "Respect for user's motion preferences (prefers-reduced-motion)",
  f061: "No Auto-play:",
  f062: "Media does not auto-play with sound",
  f063: "Forms and Input",
  f064: "Clear Labels:",
  f065: "Every form field has a visible and programmatic label",
  f066: "Error Identification:",
  f067: "Form errors are clearly identified and described",
  f068: "Required Fields:",
  f069: "Required fields are clearly marked",
  f070: "Input Assistance:",
  f071: "Instructions provided for complex inputs",
  f072: "Known Limitations",
  f073: "Despite our efforts to ensure accessibility, some limitations may still exist. We are aware of the following areas that require ongoing improvement:",
  f074: "Third-Party Content:",
  f075: "Some embedded third-party content (maps, videos, social media feeds) may have accessibility limitations outside our control",
  f076: "PDF Documents:",
  f077: "Some downloadable PDF documents may not be fully accessible. We can provide alternative formats upon request",
  f078: "Complex Interactions:",
  f079: "Some advanced interactive features may present challenges for certain assistive technologies",
  f080: "Historical Content:",
  f081: "Older content predating our current accessibility standards may not meet WCAG 2.0 Level AA",
  f082: "We are actively working to address these limitations and welcome your feedback on any accessibility barriers you encounter.",
  f083: "Compatible Technologies",
  f084: "This website is designed to be compatible with the following assistive technologies:",
  f085: "Screen Readers:",
  f086: "NVDA, JAWS, VoiceOver, TalkBack",
  f087: "Screen Magnification:",
  f088: "ZoomText, built-in browser zoom",
  f089: "Speech Recognition:",
  f090: "Dragon NaturallySpeaking, Windows Speech Recognition",
  f091: "Alternative Input Devices:",
  f092: "Switch controls, head pointers, eye-tracking devices",
  f093: "Supported Browsers:",
  f094: "Chrome, Firefox, Safari, Edge (latest versions)",
  f095: "Testing and Validation",
  f096: "We employ multiple testing methods to ensure accessibility:",
  f097: "Automated Testing:",
  f098: "WAVE, axe DevTools, Lighthouse audits",
  f099: "Manual Testing:",
  f100: "Keyboard navigation, screen reader testing, color contrast verification",
  f101: "User Testing:",
  f102: "Feedback from users with disabilities",
  f103: "Code Review:",
  f104: "Regular review of HTML, CSS, and JavaScript for accessibility",
  f105: "Regular Audits:",
  f106: "Periodic comprehensive accessibility audits",
  f107: "Alternative Formats and Assistance",
  f108: "We are committed to providing information in accessible formats when needed. If you encounter content that is not accessible to you:",
  f109: "Request Alternative Formats",
  f110: "We can provide information in alternative formats such as:",
  f111: "Large print documents",
  f112: "Plain text versions of web content",
  f113: "Accessible PDF versions",
  f114: "Audio descriptions",
  f115: "Information via phone or email",
  f116: "How to Request Assistance",
  f117: "Contact our accessibility team:",
  f118: "Email:",
  f119: "Phone:",
  f120: "Response Time:",
  f121: "We aim to respond within 2 business days",
  f122: "Feedback and Reporting Issues",
  f123: "We welcome your feedback on the accessibility of our website. If you encounter an accessibility barrier or have suggestions for improvement:",
  f124: "Report an Accessibility Issue",
  f125: "When reporting an issue, please include:",
  f126: "Description of the issue and how it affects you",
  f127: "The page or section where you encountered the problem",
  f128: "The assistive technology and browser you are using",
  f129: "Any suggestions for improvement",
  f130: "Contact Information",
  f131: "Accessibility Coordinator",
  f132: "Email: ",
  f133: "Phone: ",
  f134: "Or use our ",
  f135: "contact form",
  f136: '(Subject: "Accessibility Feedback")',
  f137: "Ongoing Efforts and Improvements",
  f138: "Accessibility is an ongoing effort. We are continuously working to improve the accessibility of our website through:",
  f139: "Regular accessibility audits and testing",
  f140: "Staff training on accessibility best practices",
  f141: "Incorporating accessibility into our design and development process",
  f142: "Monitoring and implementing new accessibility standards and techniques",
  f143: "Responding to user feedback and addressing reported issues",
  f144: "Reviewing and updating third-party tools and plugins for accessibility",
  f145: "Standards and Guidelines",
  f146: "Our accessibility efforts are guided by:",
  f147: "WCAG 2.0:",
  f148: "Web Content Accessibility Guidelines 2.0 Level AA",
  f149: "AODA:",
  f150: "Accessibility for Ontarians with Disabilities Act",
  f151: "IASR:",
  f152: "Integrated Accessibility Standards Regulation (Ontario Reg. 191/11)",
  f153: "WAI-ARIA:",
  f154: "Web Accessibility Initiative - Accessible Rich Internet Applications",
  f155: "Learn more about WCAG 2.0: ",
  f156: "WCAG 2.0 Quick Reference",
  f157: "Third-Party Content",
  f158: "Our website may include content from third-party providers (Google Maps, YouTube, social media platforms). While we strive to ensure all content is accessible, we cannot always guarantee the accessibility of third-party content.",
  f159: "If you experience difficulties with third-party content, please contact us, and we will work to provide the information in an alternative format.",
  f160: "Formal Complaints Process",
  f161: "If you are not satisfied with our response to an accessibility concern, you may:",
  f162: "Contact our Accessibility Coordinator to escalate your concern",
  f163: "File a complaint with the Accessibility Directorate of Ontario",
  f164: "Contact the Ontario Human Rights Commission",
  f165: "External Resources:",
  f166: "Accessibility Directorate of Ontario:",
  f167: "ontario.ca/accessibility",
  f168: "Ontario Human Rights Commission:",
  f169: "ohrc.on.ca",
  f170: "Statement Review and Updates",
  f171: "This Accessibility Statement is reviewed and updated regularly to reflect our current efforts and the evolving accessibility landscape.",
  f172: "Last Review Date:",
  f173: "Next Scheduled Review:",
  f174: "Contact Our Accessibility Team",
  f175: "We are here to help. If you have questions, feedback, or need assistance accessing our website or services:",
  f176: "Ascent Group Construction - Accessibility Team",
  f177: "Email: ",
  f178: "Phone: ",
  f179: "Contact Form: ",
  f180: "ascentgroupconstruction.com/contact",
};
export const meta = {
  f001: {
    label: "Accessibility Statement | Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 438,
    locked: false,
  },
  f005: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "Accessibility Statement",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "Last Updated: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "Our Commitment to Accessibility",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label:
      "Ascent Group Construction is committed to ensuring digital accessibili",
    section: "Page copy",
    kind: "text",
    maxLength: 786,
    locked: false,
  },
  f010: {
    label:
      "We are committed to complying with the Accessibility for Ontarians wit",
    section: "Page copy",
    kind: "text",
    maxLength: 588,
    locked: false,
  },
  f011: {
    label: "Conformance Status",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "Conformance Level:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "WCAG 2.0 Level AA (Partial Conformance)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label:
      "Partial conformance means that some parts of the content do not fully ",
    section: "Page copy",
    kind: "text",
    maxLength: 483,
    locked: false,
  },
  f015: {
    label:
      "Our website has been designed with accessibility in mind and tested us",
    section: "Page copy",
    kind: "text",
    maxLength: 609,
    locked: false,
  },
  f016: {
    label: "Accessibility Features",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Our website includes the following accessibility features:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "Keyboard Navigation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Skip Links:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Skip to main content links on all pages",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Logical Tab Order:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "Keyboard navigation follows a logical sequence",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Focus Indicators:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Clear visual indicators show keyboard focus",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "No Keyboard Traps:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "All interactive elements are keyboard accessible",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Screen Reader Support",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Semantic HTML:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Proper use of HTML5 semantic elements",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "ARIA Landmarks:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "Page regions identified with ARIA landmarks",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "ARIA Labels:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Descriptive labels for interactive elements",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "Alt Text:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "Alternative text for all meaningful images",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "Form Labels:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "Clear labels and instructions for all form fields",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Visual Accessibility",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Color Contrast:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label:
      "Text meets WCAG AA contrast ratios (4.5:1 for normal text, 3:1 for lar",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Resizable Text:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "Text can be resized up to 200% without loss of functionality",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f043: {
    label: "Color Independence:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "Information is not conveyed by color alone",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "Responsive Design:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "Content adapts to different screen sizes and orientations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "Content Structure",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "Heading Hierarchy:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "Proper use of heading levels (H1-H6)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Descriptive Links:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Link text describes the destination or purpose",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "List Markup:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "Lists are properly marked up with semantic HTML",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "Table Headers:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "Data tables include proper header associations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "Media and Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "Video Captions:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "Videos include captions where applicable",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "Reduced Motion:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Respect for user's motion preferences (prefers-reduced-motion)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "No Auto-play:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "Media does not auto-play with sound",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "Forms and Input",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "Clear Labels:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "Every form field has a visible and programmatic label",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "Error Identification:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "Form errors are clearly identified and described",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "Required Fields:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "Required fields are clearly marked",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "Input Assistance:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "Instructions provided for complex inputs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "Known Limitations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label:
      "Despite our efforts to ensure accessibility, some limitations may stil",
    section: "Page copy",
    kind: "text",
    maxLength: 444,
    locked: false,
  },
  f074: {
    label: "Third-Party Content:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label:
      "Some embedded third-party content (maps, videos, social media feeds) m",
    section: "Page copy",
    kind: "text",
    maxLength: 369,
    locked: false,
  },
  f076: {
    label: "PDF Documents:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label:
      "Some downloadable PDF documents may not be fully accessible. We can pr",
    section: "Page copy",
    kind: "text",
    maxLength: 324,
    locked: false,
  },
  f078: {
    label: "Complex Interactions:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label:
      "Some advanced interactive features may present challenges for certain ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "Historical Content:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label:
      "Older content predating our current accessibility standards may not me",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label:
      "We are actively working to address these limitations and welcome your ",
    section: "Page copy",
    kind: "text",
    maxLength: 369,
    locked: false,
  },
  f083: {
    label: "Compatible Technologies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label:
      "This website is designed to be compatible with the following assistive",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "Screen Readers:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "NVDA, JAWS, VoiceOver, TalkBack",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "Screen Magnification:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label: "ZoomText, built-in browser zoom",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label: "Speech Recognition:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f090: {
    label: "Dragon NaturallySpeaking, Windows Speech Recognition",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f091: {
    label: "Alternative Input Devices:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f092: {
    label: "Switch controls, head pointers, eye-tracking devices",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f093: {
    label: "Supported Browsers:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f094: {
    label: "Chrome, Firefox, Safari, Edge (latest versions)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f095: {
    label: "Testing and Validation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f096: {
    label: "We employ multiple testing methods to ensure accessibility:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f097: {
    label: "Automated Testing:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f098: {
    label: "WAVE, axe DevTools, Lighthouse audits",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f099: {
    label: "Manual Testing:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f100: {
    label:
      "Keyboard navigation, screen reader testing, color contrast verificatio",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f101: {
    label: "User Testing:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f102: {
    label: "Feedback from users with disabilities",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f103: {
    label: "Code Review:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f104: {
    label: "Regular review of HTML, CSS, and JavaScript for accessibility",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f105: {
    label: "Regular Audits:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f106: {
    label: "Periodic comprehensive accessibility audits",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f107: {
    label: "Alternative Formats and Assistance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f108: {
    label:
      "We are committed to providing information in accessible formats when n",
    section: "Page copy",
    kind: "text",
    maxLength: 396,
    locked: false,
  },
  f109: {
    label: "Request Alternative Formats",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f110: {
    label: "We can provide information in alternative formats such as:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f111: {
    label: "Large print documents",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f112: {
    label: "Plain text versions of web content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f113: {
    label: "Accessible PDF versions",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f114: {
    label: "Audio descriptions",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f115: {
    label: "Information via phone or email",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f116: {
    label: "How to Request Assistance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f117: {
    label: "Contact our accessibility team:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f118: {
    label: "Email:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f119: {
    label: "Phone:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f120: {
    label: "Response Time:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f121: {
    label: "We aim to respond within 2 business days",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f122: {
    label: "Feedback and Reporting Issues",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f123: {
    label:
      "We welcome your feedback on the accessibility of our website. If you e",
    section: "Page copy",
    kind: "text",
    maxLength: 420,
    locked: false,
  },
  f124: {
    label: "Report an Accessibility Issue",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f125: {
    label: "When reporting an issue, please include:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f126: {
    label: "Description of the issue and how it affects you",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f127: {
    label: "The page or section where you encountered the problem",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f128: {
    label: "The assistive technology and browser you are using",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f129: {
    label: "Any suggestions for improvement",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f130: {
    label: "Contact Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f131: {
    label: "Accessibility Coordinator",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f132: {
    label: "Email: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f133: {
    label: "Phone: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f134: {
    label: "Or use our ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f135: {
    label: "contact form",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f136: {
    label: '(Subject: "Accessibility Feedback")',
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f137: {
    label: "Ongoing Efforts and Improvements",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f138: {
    label:
      "Accessibility is an ongoing effort. We are continuously working to imp",
    section: "Page copy",
    kind: "text",
    maxLength: 348,
    locked: false,
  },
  f139: {
    label: "Regular accessibility audits and testing",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f140: {
    label: "Staff training on accessibility best practices",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f141: {
    label:
      "Incorporating accessibility into our design and development process",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f142: {
    label:
      "Monitoring and implementing new accessibility standards and techniques",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f143: {
    label: "Responding to user feedback and addressing reported issues",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f144: {
    label:
      "Reviewing and updating third-party tools and plugins for accessibility",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f145: {
    label: "Standards and Guidelines",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f146: {
    label: "Our accessibility efforts are guided by:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f147: {
    label: "WCAG 2.0:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f148: {
    label: "Web Content Accessibility Guidelines 2.0 Level AA",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f149: {
    label: "AODA:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f150: {
    label: "Accessibility for Ontarians with Disabilities Act",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f151: {
    label: "IASR:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f152: {
    label:
      "Integrated Accessibility Standards Regulation (Ontario Reg. 191/11)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f153: {
    label: "WAI-ARIA:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f154: {
    label:
      "Web Accessibility Initiative - Accessible Rich Internet Applications",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f155: {
    label: "Learn more about WCAG 2.0: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f156: {
    label: "WCAG 2.0 Quick Reference",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f157: {
    label: "Third-Party Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f158: {
    label:
      "Our website may include content from third-party providers (Google Map",
    section: "Page copy",
    kind: "text",
    maxLength: 684,
    locked: false,
  },
  f159: {
    label:
      "If you experience difficulties with third-party content, please contac",
    section: "Page copy",
    kind: "text",
    maxLength: 435,
    locked: false,
  },
  f160: {
    label: "Formal Complaints Process",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f161: {
    label:
      "If you are not satisfied with our response to an accessibility concern",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f162: {
    label: "Contact our Accessibility Coordinator to escalate your concern",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f163: {
    label: "File a complaint with the Accessibility Directorate of Ontario",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f164: {
    label: "Contact the Ontario Human Rights Commission",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f165: {
    label: "External Resources:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f166: {
    label: "Accessibility Directorate of Ontario:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f167: {
    label: "ontario.ca/accessibility",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f168: {
    label: "Ontario Human Rights Commission:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f169: {
    label: "ohrc.on.ca",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f170: {
    label: "Statement Review and Updates",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f171: {
    label:
      "This Accessibility Statement is reviewed and updated regularly to refl",
    section: "Page copy",
    kind: "text",
    maxLength: 405,
    locked: false,
  },
  f172: {
    label: "Last Review Date:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f173: {
    label: "Next Scheduled Review:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f174: {
    label: "Contact Our Accessibility Team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f175: {
    label:
      "We are here to help. If you have questions, feedback, or need assistan",
    section: "Page copy",
    kind: "text",
    maxLength: 321,
    locked: false,
  },
  f176: {
    label: "Ascent Group Construction - Accessibility Team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f177: {
    label: "Email: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f178: {
    label: "Phone: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f179: {
    label: "Contact Form: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f180: {
    label: "ascentgroupconstruction.com/contact",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
  },
} as const;
const module = defineContent("accessibility", defaults, meta);
export const schema = module.schema;
export default module;
