import { defineContent } from "../types";
export const defaults = {
  f001: "Construction Insights | Envelope & Restoration Contractor",
  f002: "Expert insights on building envelope restoration, façade remediation, parking garage restoration, and real-world case studies showcasing successful specialty projects from Ascent Group Construction.",
  f003: "Loading content...",
  f004: "Blog & Case Studies",
  f005: "Expert insights, success stories, and real-world projects from industry professionals",
  f006: "Construction insights and case studies",
  f007: "Home",
  f008: "Blog & Case Studies",
  f009: "Coming Soon",
  f010: "We're launching our content library. Check back soon for insights on building envelope restoration, project planning, and specialty contracting.",
  f011: "Blog & Case Studies",
  f012: "Expert insights, success stories, and real-world projects from industry professionals",
  f013: "Construction insights and case studies",
  f014: "Home",
  f015: "Blog & Case Studies",
  f016: "Featured Content",
  f017: "Latest insights and success stories from our team",
  f018: "All Content",
  f019: "Browse our complete library of articles and case studies",
  f020: "Load More Articles",
  f021: "No articles found in this category.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 594,
    locked: false,
  },
  f003: {
    label: "Loading content...",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "Coming Soon",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label:
      "We're launching our content library. Check back soon for insights on b",
    section: "Page copy",
    kind: "text",
    maxLength: 432,
    locked: false,
  },
  f011: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Featured Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Latest insights and success stories from our team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "All Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Browse our complete library of articles and case studies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Load More Articles",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "No articles found in this category.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("blog", defaults, meta);
export const schema = module.schema;
export default module;
