import { defineContent } from "../types";
export const defaults = {
  f001: "Safety",
  f002: "Every crew member goes home safe. We invest in proper training, equipment, and protocols because there is no shortcut to safety.",
  f003: "Quality",
  f004: "We self-perform the work, so our name is on every detail. Consistent execution and pride in craftsmanship define how we operate.",
  f005: "Accountability",
  f006: "One crew, one point of contact, direct responsibility. We own the work from start to finish and stand behind it.",
  f007: "Growth",
  f008: "We're building something. Team members who want to grow with a company—not just fill a seat—find real opportunity here.",
  f009: "Envelope & Coatings Installers",
  f010: "EIFS, stucco, sealant, waterproofing membrane, and protective coating application. Experience with Dryvit, Parex, or Sto systems is valued.",
  f011: "Restoration & Masonry Trades",
  f012: "Brick and block repair, tuckpointing, concrete restoration, and balcony waterproofing. Skilled hands-on tradespeople who take pride in quality.",
  f013: "Painters & Interior Finishers",
  f014: "Commercial and residential painting, epoxy and urethane coatings, drywall finishing, and tile installation. Detail-oriented professionals.",
  f015: "Project Coordination",
  f016: "Field coordination, scheduling, documentation, and client communication. Construction background with strong organizational skills.",
  f017: "Estimating & Pre-Construction",
  f018: "Quantity takeoffs, bid preparation, and scope analysis for envelope and interior trade projects. Experience with estimating software is an asset.",
  f019: "Work With Ascent | Careers in Envelope Restoration & Interior Trades",
  f020: "Join Ascent Group Construction — a growing specialty contractor focused on building envelope restoration and interior trades across the GTA. We're looking for skilled tradespeople and coordinators who value quality, safety, and accountability.",
  f021: "Work With Ascent",
  f022: "We're a growing specialty contractor focused on building envelope and interior trades across the GTA. We're always interested in hearing from skilled, accountable people.",
  f023: "Ascent Group Construction team at work",
  f024: "Introduce Yourself",
  f025: "Home",
  f026: "Careers",
  f027: "Who We Are",
  f028: "Ascent Group is a specialty contractor with a focused crew delivering building envelope restoration, coatings, and interior trades across Ontario's Greater Toronto Area. We self-perform the majority of our work — which means our people are the product.",
  f029: "We're not a large company. We're a disciplined, growing team that values doing the work right, communicating clearly, and building a reputation project by project.",
  f030: "What We Value",
  f031: "These aren't corporate buzzwords — they're how we actually operate",
  f032: "Trades & Roles We're Looking For",
  f033: "We don't always have formal openings posted — but we're always open to hearing from the right people",
  f034: "How to Connect",
  f035: "If you're a skilled tradesperson, coordinator, or estimator looking for a company that values quality work and treats people with respect — we'd like to hear from you.",
  f036: "Send us your resume and a brief note about your experience. We review every submission and will reach out if there's a fit — now or in the future.",
  f037: "Valid Working at Heights certification is an asset",
  f038: "Valid Ontario driver's license preferred for field roles",
  f039: "All experience levels considered — willingness to learn matters",
  f040: "Introduce Yourself",
  f041: "Submit your resume and we'll keep you on file. When the right opportunity comes up, we'll reach out directly.",
  f042: "Submit Your Resume",
  f043: "Careers FAQ",
  f044: "Common questions about working with Ascent Group",
  f045: "Learn More About Ascent",
  f046: "Explore who we are and how we work before you reach out.",
  f047: "Our Story",
  f048: "How we were founded and what drives the team.",
  f049: "Our Process",
  f050: "How a typical project moves from inquiry to closeout.",
  f051: "Capabilities",
  f052: "What we self-perform and how we deliver.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 384,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 357,
    locked: false,
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 417,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f011: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 429,
    locked: false,
  },
  f013: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 414,
    locked: false,
  },
  f015: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 393,
    locked: false,
  },
  f017: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 435,
    locked: false,
  },
  f019: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 729,
    locked: false,
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 510,
    locked: false,
  },
  f023: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Who We Are",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label:
      "Ascent Group is a specialty contractor with a focused crew delivering ",
    section: "Page copy",
    kind: "text",
    maxLength: 756,
    locked: false,
  },
  f029: {
    label:
      "We're not a large company. We're a disciplined, growing team that valu",
    section: "Page copy",
    kind: "text",
    maxLength: 489,
    locked: false,
  },
  f030: {
    label: "What We Value",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "These aren't corporate buzzwords — they're how we actually operate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "Trades & Roles We're Looking For",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label:
      "We don't always have formal openings posted — but we're always open to",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "How to Connect",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label:
      "If you're a skilled tradesperson, coordinator, or estimator looking fo",
    section: "Page copy",
    kind: "text",
    maxLength: 501,
    locked: false,
  },
  f036: {
    label:
      "Send us your resume and a brief note about your experience. We review ",
    section: "Page copy",
    kind: "text",
    maxLength: 438,
    locked: false,
  },
  f037: {
    label: "Valid Working at Heights certification is an asset",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f038: {
    label: "Valid Ontario driver's license preferred for field roles",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "All experience levels considered — willingness to learn matters",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "Introduce Yourself",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label:
      "Submit your resume and we'll keep you on file. When the right opportun",
    section: "Page copy",
    kind: "text",
    maxLength: 327,
    locked: false,
  },
  f042: {
    label: "Submit Your Resume",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "Careers FAQ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "Common questions about working with Ascent Group",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("careers", defaults, meta);
export const schema = module.schema;
export default module;
