import { defineContent } from "../types";
export const defaults = {
  f001: "Service Area Not Found",
  f002: "The requested service area could not be found.",
  f003: "Location Not Found",
  f004: "The service area you're looking for doesn't exist.",
  f005: "View All Service Areas",
  f006: "Home",
  f007: "Service Areas",
  f008: "Get Estimate",
  f009: "Home",
  f010: "Service Areas",
  f011: "Call Us",
  f012: "Hours",
  f013: "Mon-Fri 8AM-6PM",
  f014: "Serving",
  f015: "& Area",
  f016: "Services in ",
  f017: "Complete building envelope and restoration solutions for ",
  f018: "properties",
  f019: "Who We Serve in ",
  f020: "Property Managers",
  f021: "Multi-family and commercial building maintenance",
  f022: "General Contractors",
  f023: "Trade partner for envelope scopes",
  f024: "Developers",
  f025: "New construction envelope systems",
  f026: "Homeowners",
  f027: "Residential exterior services",
  f028: "Serving ",
  f029: "Crews dispatched from our GTA base. Same-day response available for emergency envelope failures within the core service radius.",
  f030: "Popular Services in ",
  f031: "Explore our most-requested specialty trade services for ",
  f032: "properties.",
  f033: "Available in ",
  f034: "View All Services",
  f035: "Recent Projects in ",
  f036: "A selection of completed work in and around ",
  f037: "View All Projects",
  f038: "Other Service Areas",
  f039: "We also serve these nearby communities",
  f040: "View All Service Areas",
  f041: "Ready to Start Your ",
  f042: "Project?",
  f043: "Get a detailed proposal from our team. Free site assessments for commercial projects.",
  f044: "Get Estimate",
  f045: "Building Envelope Solutions",
  f046: "Waterproofing Systems",
  f047: "EIFS & Stucco Systems",
  f048: "Cladding Systems",
  f049: "Painting Services",
  f050: "Parking Garage Restoration",
  f051: "Sealant Programs",
  f052: "Sustainable Building",
  f053: "Toronto",
  f054: "As Ontario's largest city, Toronto is home to countless commercial, multi-family, and institutional buildings requiring expert building envelope and restoration services. From downtown high-rises to suburban complexes, Ascent Group Construction delivers professional façade remediation, waterproofing, and specialty contractor services throughout Toronto.",
  f055: "Mississauga",
  f056: "Mississauga's rapidly growing commercial and residential landscape demands reliable building envelope contractors. Our team provides comprehensive restoration, EIFS, masonry repair, and protective coating services to property managers and building owners throughout Mississauga.",
  f057: "Brampton",
  f058: "Brampton's expanding infrastructure requires trusted specialty contractors for building envelope maintenance and restoration. Ascent Group Construction serves commercial, industrial, and multi-family properties with professional cladding, waterproofing, and coating services.",
  f059: "Vaughan",
  f060: "From Woodbridge to Maple, Vaughan's commercial and residential buildings benefit from our expert building envelope services. Our crews deliver quality EIFS installation, masonry restoration, and façade repairs throughout Vaughan.",
  f061: "Markham",
  f062: "Markham's diverse building stock—from tech campuses to residential towers—requires specialized envelope contractors. Ascent Group provides comprehensive restoration, waterproofing, and cladding services to Markham property owners.",
  f063: "Richmond Hill",
  f064: "Richmond Hill's growing community includes many commercial and multi-family buildings needing professional envelope maintenance. Our team delivers quality façade remediation, coating systems, and restoration services.",
  f065: "Oakville",
  f066: "Oakville's premium commercial and residential properties deserve expert building envelope services. Ascent Group provides meticulous restoration, waterproofing, and protective coating solutions throughout Oakville.",
  f067: "Burlington",
  f068: "Burlington's lakeside commercial district and residential communities benefit from our comprehensive building envelope services. We deliver professional façade repairs, cladding installation, and waterproofing throughout Burlington.",
  f069: "Hamilton",
  f070: "Hamilton's industrial heritage and growing commercial sector require experienced specialty contractors. Ascent Group serves Hamilton with expert masonry restoration, protective coatings, and building envelope solutions.",
  f071: "Ajax",
  f072: "Ajax's commercial and residential buildings benefit from our professional building envelope services. We provide quality restoration, waterproofing, and cladding solutions throughout Ajax.",
  f073: "Pickering",
  f074: "Pickering's growing infrastructure requires reliable specialty contractors. Ascent Group delivers professional façade remediation, EIFS, and envelope restoration services throughout Pickering.",
  f075: "Whitby",
  f076: "Whitby's commercial and multi-family properties benefit from our comprehensive envelope solutions. We provide professional restoration, coating, and waterproofing services throughout Whitby.",
  f077: "Oshawa",
  f078: "Oshawa's diverse building stock requires experienced envelope contractors. Ascent Group serves Oshawa with expert façade repairs, masonry restoration, and protective coating systems.",
  f079: "Newmarket",
  f080: "Newmarket's commercial and residential properties benefit from our building envelope expertise. We deliver quality EIFS, cladding, and restoration services throughout Newmarket.",
  f081: "Aurora",
  f082: "Aurora's premium properties deserve expert building envelope care. Ascent Group provides professional façade remediation, waterproofing, and coating services throughout Aurora.",
  f083: "Milton",
  f084: "Milton's rapidly growing commercial and residential developments require reliable specialty contractors. We deliver professional envelope restoration and cladding services throughout Milton.",
  f085: "King City",
  f086: "King City's estate homes and commercial properties benefit from expert building envelope care. Ascent Group provides professional façade remediation, EIFS, masonry restoration, and protective coating services throughout King City and the surrounding area.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "Location Not Found",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "The service area you're looking for doesn't exist.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "View All Service Areas",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "Call Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "Hours",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "Mon-Fri 8AM-6PM",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "Serving",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "& Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Services in ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Complete building envelope and restoration solutions for ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "properties",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Who We Serve in ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Property Managers",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Multi-family and commercial building maintenance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "General Contractors",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Trade partner for envelope scopes",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Developers",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "New construction envelope systems",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Homeowners",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Residential exterior services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Serving ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label:
      "Crews dispatched from our GTA base. Same-day response available for em",
    section: "Page copy",
    kind: "text",
    maxLength: 381,
    locked: false,
  },
  f030: {
    label: "Popular Services in ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "Explore our most-requested specialty trade services for ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "properties.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Available in ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "View All Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "Recent Projects in ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "A selection of completed work in and around ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "View All Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Other Service Areas",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "We also serve these nearby communities",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "View All Service Areas",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Ready to Start Your ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "Project?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label:
      "Get a detailed proposal from our team. Free site assessments for comme",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "Get Estimate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1065,
    locked: false,
  },
  f055: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 834,
    locked: false,
  },
  f057: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 825,
    locked: false,
  },
  f059: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 687,
    locked: false,
  },
  f061: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 690,
    locked: false,
  },
  f063: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 651,
    locked: false,
  },
  f065: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 642,
    locked: false,
  },
  f067: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 696,
    locked: false,
  },
  f069: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 657,
    locked: false,
  },
  f071: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 564,
    locked: false,
  },
  f073: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 576,
    locked: false,
  },
  f075: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 570,
    locked: false,
  },
  f077: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 546,
    locked: false,
  },
  f079: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 531,
    locked: false,
  },
  f081: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 528,
    locked: false,
  },
  f083: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 570,
    locked: false,
  },
  f085: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 765,
    locked: false,
  },
} as const;
const module = defineContent("city-page", defaults, meta);
export const schema = module.schema;
export default module;
