import { defineContent } from "../types";
export const defaults = {
  f001: "After-Hours Work",
  f002: "Night and weekend scheduling available to avoid disrupting your business operations",
  f003: "Fast-Track Scheduling",
  f004: "Accelerated timelines when you need to meet tight deadlines",
  f005: "Fully Insured",
  f006: "$2M CGL liability coverage and WSIB compliance—your business is protected",
  f007: "Minimal Disruption",
  f008: "Strategic planning and execution that keeps your business running smoothly",
  f009: "Low-VOC Materials",
  f010: "Zero-odor, environmentally friendly products safe for occupied spaces",
  f011: "Office Buildings",
  f012: "Professional finishes that create productive, attractive workspaces",
  f013: "After-hours scheduling",
  f014: "Floor-by-floor coordination",
  f015: "Common area refresh",
  f016: "Conference room upgrades",
  f017: "Retail & Hospitality",
  f018: "Fast turnarounds that minimize impact on customer-facing operations",
  f019: "Quick rebrands",
  f020: "Night-shift work",
  f021: "Storefront painting",
  f022: "Seasonal updates",
  f023: "Industrial & Warehouses",
  f024: "Durable coatings and safety markings for high-traffic environments",
  f025: "Epoxy floor coatings",
  f026: "Safety line striping",
  f027: "Machinery areas",
  f028: "Loading docks",
  f029: "Healthcare & Education",
  f030: "Specialized finishes meeting strict regulatory and safety standards",
  f031: "Antimicrobial coatings",
  f032: "Low-VOC products",
  f033: "School break scheduling",
  f034: "Patient area coordination",
  f035: "Site Review & Scope Definition",
  f036: "We visit your facility to assess condition, identify priorities, and define scope around your operational schedule",
  f037: "Proposal & Scheduling",
  f038: "Detailed proposal with phased approach, material specifications, and scheduling options that minimize business disruption",
  f039: "Coordinated Execution",
  f040: "After-hours and weekend work where needed. Daily progress updates and direct communication with your facility manager",
  f041: "Closeout & Documentation",
  f042: "Final walkthrough, deficiency resolution, warranty documentation, and maintenance recommendations",
  f043: "Commercial Building Envelope & Restoration Services - Toronto & GTA",
  f044: "Envelope repairs, waterproofing, and restoration for office buildings, retail properties, and industrial facilities. After-hours scheduling. Minimal disruption. 15+ years of combined team experience in commercial construction.",
  f045: "For Commercial Clients",
  f046: "Envelope & Restoration for Commercial Properties",
  f047: "Office buildings, retail strips, industrial properties—façade repairs, waterproofing, and interior finishes. After-hours scheduling available to minimize business disruption.",
  f048: "Commercial construction services",
  f049: "Request an Estimate",
  f050: "Home",
  f051: "Commercial Clients",
  f052: "After-Hours Available",
  f053: "Minimal Disruption",
  f054: "Fully Insured",
  f055: "Why Commercial Clients Choose Ascent",
  f056: "Envelope and restoration services designed to protect your building investment with minimal business disruption.",
  f057: "Industries We Serve",
  f058: "Specialized solutions for every commercial sector",
  f059: "Our Commercial Approach",
  f060: "A clear process designed around your facility's operational needs",
  f061: "Operational Standards",
  f062: "Built for commercial project requirements",
  f063: "Common Questions from Commercial Owners",
  f064: "After-hours work, low-VOC materials, phased execution, and insurance — covered.",
  f065: "Ready to Elevate Your Facility?",
  f066: "Get a comprehensive commercial quote with flexible scheduling options",
  f067: "Request an Estimate",
  f068: "Contact Us",
  f069: "Explore Related Services",
  f070: "Property Manager Programs",
  f071: "Multi-residential capital planning and recurring envelope maintenance for portfolio managers.",
  f072: "Emergency Building Repair",
  f073: "Same-day site response for active leaks, facade failures, and storm damage on commercial properties.",
  f074: "Full Service Catalogue",
  f075: "Building envelope, restoration, and interior trade scopes across our commercial portfolio.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 342,
    locked: false,
  },
  f037: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 363,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 351,
    locked: false,
  },
  f041: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 678,
    locked: false,
  },
  f045: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 522,
    locked: false,
  },
  f048: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: false,
  },
  f057: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f065: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("commercial-clients", defaults, meta);
export const schema = module.schema;
export default module;
