import { defineContent } from "../types";
export const defaults = {
  f001: "Professional Standards",
  f002: "15+ years of combined team experience in commercial and multi-unit construction",
  f003: "GTA Project Experience",
  f004: "15+ years of combined team experience across GTA commercial projects",
  f005: "Fast-Track Capability",
  f006: "Dedicated crews and equipment to meet aggressive development timelines",
  f007: "Value Engineering",
  f008: "Cost-saving alternatives without compromising quality or building code compliance",
  f009: "New Construction Painting",
  f010: "Complete interior and exterior painting for residential and commercial developments",
  f011: "Multi-unit coordination",
  f012: "Phased completion schedules",
  f013: "Quality control inspections",
  f014: "Warranty programs",
  f015: "Building Envelope Systems",
  f016: "EIFS, stucco, masonry, and cladding installation with 15-year waterproofing warranties",
  f017: "Thermal performance optimization",
  f018: "Weather barrier integration",
  f019: "Code compliance documentation",
  f020: "System testing",
  f021: "Parkade & Infrastructure",
  f022: "Traffic coating systems, concrete restoration, and protective coatings for parking structures",
  f023: "Fast-cure systems",
  f024: "Overnight/weekend scheduling",
  f025: "Structural assessment",
  f026: "Maintenance programs",
  f027: "Pre-Qualification",
  f028: "Submit comprehensive documentation including insurance, safety records, and references",
  f029: "RFP Response",
  f030: "Detailed proposals with material specifications, crew schedules, and value engineering options",
  f031: "Contract & Coordination",
  f032: "Formalized agreements with milestone schedules integrated with your project timeline",
  f033: "Execution & Delivery",
  f034: "On-site project management, daily reporting, and quality assurance throughout construction",
  f035: "Developers & Contractors | Partnership Solutions",
  f036: "Partner with Ascent Group Construction for your development projects. 15+ years combined team experience supporting multi-unit residential and commercial projects across the GTA. Fully insured and WSIB compliant.",
  f037: "For Developers & GCs",
  f038: "Build With a Trusted Partner",
  f039: "Reliable subcontracting for painting, EIFS, stucco, and building envelope systems on mid-rise and commercial projects",
  f040: "Development and construction partnership",
  f041: "Home",
  f042: "Company",
  f043: "Developers",
  f044: "Contact Us",
  f045: "Why Developers Choose Ascent",
  f046: "Technical capability and professional standards you can count on",
  f047: "Specialized Developer Services",
  f048: "Painting and building envelope services for new construction",
  f049: "Partnership Process",
  f050: "From RFP to project completion—a streamlined approach",
  f051: "Ready to Evaluate Us?",
  f052: "Access our complete contractor documentation including insurance certificates, WSIB clearance, safety certifications, and project references.",
  f053: "Insurance: $2M CGL",
  f054: "WSIB Clearance Certificate",
  f055: "Working Toward COR",
  f056: "Project References",
  f057: "Equipment & Crew Details",
  f058: "Quality Management System",
  f059: "Access Contractor Portal",
  f060: "Developer FAQ",
  f061: "Common questions from developers and construction managers.",
  f062: "Resources for Developers",
  f063: "Capability and procurement resources for development partners.",
  f064: "Capabilities",
  f065: "What we self-perform on mid-rise and commercial.",
  f066: "Certifications & Insurance",
  f067: "$2M CGL, WSIB, manufacturer listings.",
  f068: "Contractor Portal",
  f069: "Vendor packet and unit rates for your team.",
  f070: "Let's Build Together",
  f071: "Discuss your upcoming development project and how we can contribute to its success",
  f072: "Contact Us",
  f073: "Submit an RFP",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f015: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f017: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f029: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 636,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f037: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 351,
    locked: false,
  },
  f040: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Ready to Evaluate Us?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label:
      "Access our complete contractor documentation including insurance certi",
    section: "Page copy",
    kind: "text",
    maxLength: 423,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f053: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f054: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f056: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "Access Contractor Portal",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Developer FAQ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "Common questions from developers and construction managers.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f067: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f068: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("company-developers", defaults, meta);
export const schema = module.schema;
export default module;
