import { defineContent } from "../types";
export const defaults = {
  f001: "Slow down!",
  f002: "Please wait a moment before submitting again.",
  f003: "Too many submissions",
  f004: "Please try again in a few minutes.",
  f005: "Message sent!",
  f006: "Validation Error",
  f007: "Error",
  f008: "Failed to send message. Please try again.",
  f009: "Contact Us | Ascent Group Construction",
  f010: "Contact Ascent Group Construction for building envelope, restoration, and specialty trade services across Ontario. Request a consultation or get a project quote.",
  f011: "Contact Us",
  f012: "Get expert building envelope and restoration services across Ontario. Our specialized crews are ready to discuss your project.",
  f013: "Contact Ascent Group Construction",
  f014: "Home",
  f015: "Contact",
  f016: "Fast Response",
  f017: "Free Consultations",
  f018: "No Obligation",
  f019: "Not sure which form to use? Choose the best path for your needs:",
  f020: "General Inquiry",
  f021: "Questions, site visits, consultations",
  f022: "Project Estimate",
  f023: "Get preliminary pricing for defined scopes",
  f024: "Submit RFP",
  f025: "Formal proposals with drawings & specs",
  f026: "Send Us a Message",
  f027: "Fill out the form below and our team will get back to you within one business day.",
  f028: "Full Name *",
  f030: "Email *",
  f032: "Phone",
  f034: "Company",
  f036: "Project Details *",
  f039: "I consent to Ascent Group Construction contacting me about my inquiry via email or phone. *",
  f041: "I'd also like to receive construction industry insights and project updates. ",
  f042: "Privacy Policy",
  f043: "Website",
  f045: "Sending...",
  f046: "Submit Request",
  f047: "$2M Insured",
  f048: "WSIB Compliant",
  f049: "Your information is secure and will only be used to respond to your inquiry.",
  f050: "Contact Information",
  f051: "Office",
  f052: "Phone",
  f053: "Email",
  f054: "Business Hours",
  f055: "What to Expect",
  f056: "We typically respond within 1 business day",
  f057: "Your inquiry goes directly to our project team",
  f058: "No automated responses — real people, real answers",
  f059: "Need a formal proposal?",
  f060: "For projects with drawings, specs, or detailed scope requirements, use our RFP submission form.",
  f061: "Submit RFP",
  f062: "Our Service Area",
  f063: "Proudly serving the Greater Toronto Area and Ontario",
  f064: "Ascent Group Construction Service Area - Greater Toronto Area",
  f065: "People Also Ask",
  f066: "Common questions about contacting Ascent Group.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 483,
    locked: false,
  },
  f011: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 378,
    locked: false,
  },
  f013: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Not sure which form to use? Choose the best path for your needs:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "General Inquiry",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Questions, site visits, consultations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "Project Estimate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Get preliminary pricing for defined scopes",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Submit RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Formal proposals with drawings & specs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Send Us a Message",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label:
      "Fill out the form below and our team will get back to you within one b",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Full Name *",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "Email *",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "Phone",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "Company",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "Project Details *",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label:
      "I consent to Ascent Group Construction contacting me about my inquiry ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label:
      "I'd also like to receive construction industry insights and project up",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "Privacy Policy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "Sending...",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "Submit Request",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "$2M Insured",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f048: {
    label: "WSIB Compliant",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f049: {
    label:
      "Your information is secure and will only be used to respond to your in",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Contact Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Office",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "Phone",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "Email",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "Business Hours",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "What to Expect",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "We typically respond within 1 business day",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "Your inquiry goes directly to our project team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "No automated responses — real people, real answers",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "Need a formal proposal?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label:
      "For projects with drawings, specs, or detailed scope requirements, use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "Submit RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "Our Service Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "Proudly serving the Greater Toronto Area and Ontario",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("contact", defaults, meta);
export const schema = module.schema;
export default module;
