import { defineContent } from "../types";
export const defaults = {
  f001: "Estimate Request Submitted!",
  f002: "Validation Error",
  f003: "Request Timeout",
  f004: "The request is taking longer than expected. Please try again.",
  f005: "Submission Error",
  f006: "There was an error submitting your request. Please try again.",
  f007: "Request Project Estimate | Ascent Group Construction",
  f008: "Request a project estimate for building envelope, restoration, or specialty trade work. Fast, accurate pricing with no obligation. Licensed and insured contractors serving Ontario.",
  f009: "Request a Project Estimate",
  f010: "Project Estimator",
  f011: "Answer a few questions about your project and receive a preliminary estimate. Our team follows up within 24 hours to discuss scope and next steps.",
  f012: "Request a project estimate from Ascent Group Construction",
  f013: "Home",
  f014: "Request Estimate",
  f016: "Certified",
  f018: "CGL Coverage",
  f020: "Response Time",
  f022: "Project Manager",
  f023: "Requesting a quote for: ",
  f024: "Project Estimate",
  f025: "Get preliminary pricing for defined scopes",
  f026: "Submit RFP",
  f027: "Formal proposals with drawings & specs",
  f028: "General Inquiry",
  f029: "Questions, site visits, or consultations",
  f030: "Estimate Request Submitted",
  f031: "Thank you for your request. Our team will review your project details and contact you within 24 hours to discuss next steps.",
  f032: "A confirmation has been sent to your email address.",
  f033: "Return Home",
  f034: "Submit an RFP",
  f035: "Step ",
  f036: "of ",
  f037: "% Complete",
  f038: "Back",
  f039: "Next",
  f040: "Submit Request",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 540,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 438,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f012: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f018: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f020: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Requesting a quote for: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Project Estimate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Get preliminary pricing for defined scopes",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Submit RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Formal proposals with drawings & specs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "General Inquiry",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Questions, site visits, or consultations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "Estimate Request Submitted",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label:
      "Thank you for your request. Our team will review your project details ",
    section: "Page copy",
    kind: "text",
    maxLength: 372,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f032: {
    label: "A confirmation has been sent to your email address.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Return Home",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "Submit an RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "Step ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "of ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "% Complete",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Back",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Next",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "Submit Request",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("estimate", defaults, meta);
export const schema = module.schema;
export default module;
