import { defineContent } from "../types";
export const defaults = {
  f001: "How long has Ascent Group Construction been in business?",
  f002: "Ascent Group Construction was established in 2025 by construction professionals with 15+ years of combined experience in building envelope and interior trades work. While we're a new company, our team members bring hands-on expertise from a wide range of highrise and commercial projects across the Greater Toronto Area.",
  f003: "What areas do you serve in Ontario?",
  f004: "We serve the entire Greater Toronto Area (GTA) including Toronto, Mississauga, Brampton, Vaughan, Markham, Richmond Hill, Oakville, Burlington, and surrounding municipalities. We're equipped to handle projects throughout Southern Ontario.",
  f005: "Are you licensed and insured?",
  f006: "Yes, we are fully licensed and insured with $2M commercial general liability (CGL) coverage and full WSIB compliance for workers' compensation. We maintain comprehensive insurance and follow all Ontario construction regulations. Payment and performance bonds can be arranged through our surety partners for projects requiring them. We can provide proof of insurance and clearance certificates upon request.",
  f007: "How do I know if you're the right contractor for my project?",
  f008: "We specialize in building envelope and restoration work — including façade remediation, waterproofing, EIFS and stucco systems, masonry restoration, cladding, and interior finishing. If your project involves any of these scopes in the GTA or Southern Ontario, we're likely a strong fit. We work directly with property owners, developers, property managers, and general contractors as a specialty prime contractor.",
  f009: "How much does commercial construction cost in Toronto?",
  f010: "Commercial construction in Toronto varies widely by project scope. Tenant improvements range from $50-$200 per square foot, while new construction can exceed $250-$500 per square foot depending on complexity, finishes, and building systems. A 10,000 sq ft buildout averages $500,000-$1.5M. We provide detailed estimates with line-item breakdowns.",
  f011: "What's included in your construction estimates?",
  f012: "Our estimates include all materials, labor, equipment, permits, project management, insurance, and warranty. We break down costs by scope so you understand exactly what you're paying for. No hidden fees.",
  f013: "Do you offer project estimates?",
  f014: "Yes! We provide no-obligation estimates for all projects. For residential projects, we can often provide ballpark quotes with photos. For commercial projects, we conduct on-site visits to provide accurate, detailed estimates within 3-5 business days.",
  f015: "How much does it cost to renovate a condo unit in Mississauga?",
  f016: "A typical 2-bedroom condo unit (800-1000 sq ft) renovation in Mississauga costs $15,000-$35,000 for cosmetic updates (paint, flooring, fixtures). 3-bedroom units (1200+ sq ft) range from $25,000-$60,000. Full gut renovations can exceed $80,000-$150,000. Price varies based on finishes, scope, and structural changes.",
  f017: "What payment methods do you accept?",
  f018: "We accept checks, bank transfers (EFT), credit cards (Visa, Mastercard, Amex), and e-transfers. For projects over $10,000, we work with payment schedules: 25% deposit, 50% at midpoint, 25% on completion. No payment is due until you're completely satisfied.",
  f019: "Can I get volume pricing for multiple units?",
  f020: "Absolutely! Property managers and developers receive volume discounts for multi-unit projects. For 10+ units, expect 15-20% savings. For 50+ units, up to 30% savings. We also offer preferred pricing for annual maintenance contracts.",
  f021: "How long does a typical residential construction project take?",
  f022: "Interior renovations: 2-6 weeks for a 2000 sq ft home. Exterior renovations: 4-10 weeks depending on weather and scope. Condo unit renovations: 1-3 weeks. Major additions or new construction: 3-12 months. We provide detailed timelines during estimates and communicate daily updates throughout the project.",
  f023: "What's the best time of year for exterior construction in Ontario?",
  f024: "May through October is ideal for exterior construction in Ontario. We need suitable weather for concrete work, masonry, and exterior finishes. Late spring (May-June) and early fall (September) offer the best conditions. Some projects can proceed in winter with proper planning and temporary enclosures.",
  f025: "How long does EIFS or stucco repair take?",
  f026: "Small repairs (under 100 sq ft): 3-5 days. Medium repairs (100-500 sq ft): 1-2 weeks. Large-scale restoration: 3-6 weeks. EIFS requires proper curing time between coats (24-48 hours per layer), so timeline depends on weather and project size.",
  f027: "Can you work evenings or weekends to avoid disrupting my business?",
  f028: "Yes! We offer flexible scheduling for commercial clients including after-hours (6PM-6AM), weekends, and holiday work. After-hours work incurs a 20-30% premium but ensures zero disruption to your operations. Our team members have extensive experience working after-hours in occupied commercial buildings across the GTA.",
  f029: "Do I need to move furniture before you start?",
  f030: "We handle furniture protection and minor moving. For residential projects, please remove small valuables, wall decorations, and fragile items. We'll cover and protect all furniture and flooring with drop cloths, plastic, and padding. For complete furniture removal, we can arrange moving services at additional cost.",
  f031: "What happens if weather delays my exterior project?",
  f032: "Weather delays don't extend your contract price. We monitor forecasts closely and only work in suitable conditions (10°C+, no rain/snow, low humidity). If weather causes delays, we'll communicate immediately and reschedule to the next available window at no extra cost.",
  f033: "What brands and materials do you use?",
  f034: "We use commercial-grade materials from trusted suppliers including Benjamin Moore paints, Sherwin-Williams coatings, Dryvit EIFS systems, Hardie siding, and trusted building envelope products. We select materials based on your project requirements, durability needs, and budget. All products meet or exceed Ontario Building Code standards.",
  f035: "Can I choose my own paint colors?",
  f036: "Absolutely! We offer complimentary color consultation to help you select from 3,500+ colors across our partner brands. Our team can provide sample boards, digital mockups, and expert advice on color psychology, trends, and complementary palettes.",
  f037: "Do you use eco-friendly paints?",
  f038: "Yes, sustainability is a priority. We use low-VOC (under 50g/L) and zero-VOC paints by default. We also offer Green Seal certified products, Greenguard Gold certified options for sensitive environments, and recycled paint programs. All meet or exceed Canadian environmental standards.",
  f039: "What's the difference between paint grades?",
  f040: "Contractor grade ($30-40/gallon): Basic coverage, 3-5 year lifespan, good for rentals. Mid-grade ($45-60/gallon): Better coverage, 5-8 years, recommended for homes. Premium ($60-85/gallon): Superior coverage, 10-15 years, best for high-traffic commercial. We recommend mid-grade or premium for most projects.",
  f041: "How long will my construction project last in Ontario weather?",
  f042: "With proper construction: Building envelope systems 20-30 years, roofing 15-25 years, exterior finishes 10-20 years, interior finishes 15-30 years. Ontario's freeze-thaw cycles are harsh, so we use weather-resistant materials with proper installation. Quality construction and regular maintenance maximize lifespan.",
  f043: "What warranty do you provide on workmanship?",
  f044: "We provide a 2-year workmanship warranty on all projects covering peeling, blistering, and application defects. Materials carry manufacturer warranties (typically 5-25 years). If issues arise within warranty period, we'll return to fix at no cost. Commercial projects can extend to 5-year warranties.",
  f045: "Do you repair stucco cracks before painting?",
  f046: 'Yes, proper surface prep is critical. We repair all cracks, holes, and damaged stucco before painting using premium patching compounds and mesh. Small cracks (under 1/4"): included in painting. Large cracks or water damage: quoted separately. All stucco repairs come with 2-year warranty.',
  f047: "Can you paint brick or do you only cover it?",
  f048: "We can both paint brick and restore it. Options include: 1) Paint (permanent, good for curb appeal), 2) Limewash (breathable, traditional look), 3) Stain (enhances natural color), 4) Brick restoration (cleaning, repointing). Each has pros/cons - we'll recommend best approach for your brick type and goals.",
  f049: "What's involved in parking garage restoration?",
  f050: "Comprehensive parking garage restoration includes: concrete repair, expansion joint sealing, waterproofing membrane, traffic coating system, line striping, and bollard painting. Projects typically take 4-8 weeks depending on size. We work overnight/weekends to minimize disruption.",
  f051: "Do you install or just repair EIFS?",
  f052: "We do both! EIFS installation includes: moisture barrier, foam insulation board, base coat with mesh, finish coat, and trim details. We're certified EIFS installers with 15+ years experience. We also specialize in EIFS repairs, water damage remediation, and system upgrades.",
  f053: "Can you paint kitchen cabinets?",
  f054: "Yes! Cabinet refinishing is a specialty. Process: 1) Remove doors/hardware, 2) Clean and degrease, 3) Primer (bonding coat), 4) Two coats premium cabinet paint (Benjamin Moore Advance or Sherwin-Williams Emerald Urethane), 5) Reassemble with new hardware. Average kitchen: $3,500-$6,500, 5-7 days.",
  f055: "Do you do drywall repair and installation?",
  f056: "Yes, our team handles full drywall services: patching holes, water damage repair, texture matching, new installation, mudding, taping, and sanding. We can match any texture (orange peel, knockdown, skip trowel). Drywall services are often bundled with painting projects.",
  f057: "Can you paint high ceilings or multiple-story buildings?",
  f058: "Absolutely. We have scaffolding, boom lifts, swing stages, and specialized equipment for buildings up to 12 stories. Our team is trained and certified for high-access work with full fall protection. We've painted churches with 40-foot ceilings and 10-story condo buildings.",
  f059: "What's your typical unit turnover time for condos?",
  f060: "Standard 2-bedroom condo unit: 3 days (paint walls, ceiling, trim). With minor repairs and cleaning: 4-5 days. We coordinate with your cleaning crew and can work weekends to minimize vacancy. For 10+ unit buildings, we maintain dedicated crews for fast turnarounds.",
  f061: "Do you offer maintenance contracts for property managers?",
  f062: "Yes! Annual maintenance contracts include: quarterly inspections, priority scheduling, volume pricing (15-25% discount), dedicated account manager, 48-hour emergency response, and monthly invoicing. Perfect for condos, apartments, and commercial property portfolios.",
  f063: "Can you coordinate with tenants for interior work?",
  f064: "Absolutely. We handle all tenant communication including: access scheduling, pre-work walkthroughs, daily updates, and completion inspections. We're respectful, professional, and minimize disruption. Many property managers have us work directly with tenants to reduce their workload.",
  f065: "What's included in common area painting?",
  f066: "Common area painting includes: hallways, stairwells, lobbies, amenity rooms, elevators, parkades, and exterior common spaces. We work evenings/weekends to avoid resident disruption, use low-VOC paints for occupied buildings, and clean daily. Typical condo (100 units): 2-3 weeks.",
  f067: "Do you have WSIB coverage?",
  f068: "Yes, we maintain full WSIB (Workplace Safety & Insurance Board) clearance for all employees and subcontractors. We provide updated clearance certificates with every project proposal. Our WSIB account is in good standing.",
  f069: "What safety certifications does your team have?",
  f070: "Our team is working toward COR (Certificate of Recognition) certification. Team members hold: JHSC (Joint Health & Safety Committee) certification, Working at Heights certification, WHMIS 2015, Fall Protection, Confined Space Entry, and First Aid/CPR. We conduct regular safety training and maintain strong safety protocols on every project.",
  f071: "How do you handle lead paint in older buildings?",
  f072: "For pre-1980 buildings, we conduct lead testing ($150-300). If lead is present: 1) Containment with sealed barriers, 2) HEPA vacuums and air scrubbers, 3) Wet sanding to minimize dust, 4) Proper disposal, 5) Clearance testing. We're certified in lead-safe practices per Ontario regulations.",
  f073: "Do you need building permits for painting projects?",
  f074: "Generally no for standard repainting. However, permits may be required for: structural changes, heritage buildings, exterior color changes in some municipalities, or commercial buildings over 3 stories. We'll advise on permit requirements and handle applications if needed.",
  f075: "How much does it cost to paint a house in Toronto vs suburbs?",
  f076: "Toronto proper: 10-15% higher due to parking, permits, and access challenges. Mississauga/Brampton: baseline pricing. York Region: 5-10% lower. Downtown condo projects include costs for elevator booking, security deposits, and parking permits. Suburban houses have easier access.",
  f077: "Do Toronto condo buildings have painting restrictions?",
  f078: "Most Toronto condos require: 1) Insurance certificates for contractors, 2) Elevator booking/fees ($100-500), 3) Move-in/out permits ($50-200), 4) Work hour restrictions (usually 8AM-6PM weekdays), 5) Parking passes. We handle all paperwork and coordination with property management.",
  f079: "What neighborhoods do you serve most frequently?",
  f080: "Most projects are in: Downtown Toronto, North York, Etobicoke, Scarborough, Mississauga (Port Credit, Streetsville, Erin Mills), Brampton (Bramalea, Heart Lake), Vaughan (Woodbridge, Maple), Markham (Unionville, Thornhill), and Richmond Hill. We serve all of GTA and beyond.",
  f081: "How do you handle winter painting in Ontario?",
  f082: "Exterior painting requires 10°C+ temperatures. In winter (November-March), we focus on: 1) Interior projects, 2) Heated parkades, 3) Emergency repairs with specialty cold-weather products, 4) Planning and estimates for spring. For urgent exterior needs, we use heated tents (additional cost).",
  f083: "How much does commercial painting cost in Toronto?",
  f084: "What's the best time of year to paint exterior in Ontario?",
  f085: "Do you offer volume pricing for multiple units?",
  f086: "How long does a typical commercial construction project take?",
  f087: "How to Choose a Painting Contractor in Ontario",
  f088: "Complete guide to selecting a qualified painting contractor for your project",
  f089: "Verify Insurance",
  f090: "Check for WSIB clearance, liability insurance, and proper licensing",
  f091: "Review Portfolio",
  f092: "Examine completed projects similar to yours with photo documentation",
  f093: "Check References",
  f094: "Contact recent clients and verify satisfaction, timeline, and quality",
  f095: "Compare Quotes",
  f096: "Get 3+ detailed estimates with material and labor breakdowns",
  f097: "Review Contract",
  f098: "Ensure written agreement includes timeline, payment schedule, and warranty",
  f099: "Frequently Asked Questions | Building Envelope & Restoration",
  f100: "Get answers to 85+ questions about building envelope, restoration, and specialty trade costs, timelines, and services in Ontario and the GTA.",
  f101: "Frequently Asked Questions",
  f102: "Everything you need to know about building envelope, restoration, and specialty trade services across Ontario and the GTA.",
  f103: "Construction FAQ and answers",
  f104: "Home",
  f105: "FAQ",
  f106: "Popular Questions",
  f107: "questions",
  f108: "questions answered",
  f109: 'No questions found matching "',
  f110: "Try different keywords or browse categories above",
  f111: "Still have questions?",
  f112: "Our team is here to help. Get personalized answers from construction experts.",
  f113: "Contact Us",
  f114: "Call ",
};
export const meta = {
  f001: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 960,
    locked: true,
  },
  f003: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 714,
    locked: false,
  },
  f005: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f006: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1218,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f007: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1239,
    locked: false,
  },
  f009: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1038,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f011: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 609,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f013: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 750,
    locked: false,
  },
  f015: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 948,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f017: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 768,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f019: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 696,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f021: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 915,
    locked: false,
  },
  f023: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 906,
    locked: false,
  },
  f025: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 726,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f027: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 954,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f029: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 948,
    locked: false,
  },
  f031: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 807,
    locked: false,
  },
  f033: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1017,
    locked: false,
  },
  f035: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 738,
    locked: false,
  },
  f037: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 852,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f039: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 924,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f041: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 945,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f043: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f044: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 900,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f045: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 864,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f047: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 918,
    locked: false,
  },
  f049: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 843,
    locked: false,
  },
  f051: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 822,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f053: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 891,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 810,
    locked: false,
  },
  f057: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 819,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f059: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 795,
    locked: false,
  },
  f061: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 798,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f063: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 849,
    locked: false,
  },
  f065: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 837,
    locked: false,
  },
  f067: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f068: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 660,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f069: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 1023,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f071: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 870,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f073: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 819,
    locked: false,
  },
  f075: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 837,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f077: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 846,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f079: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 822,
    locked: false,
  },
  f081: {
    label: "question",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "answer",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 876,
    locked: false,
  },
  f083: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f090: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f091: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f092: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f093: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f094: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f095: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f096: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f097: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f098: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f099: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f100: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 423,
    locked: false,
  },
  f101: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f102: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 366,
    locked: false,
  },
  f103: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f104: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f105: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f106: {
    label: "Popular Questions",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f107: {
    label: "questions",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f108: {
    label: "questions answered",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f109: {
    label: 'No questions found matching "',
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f110: {
    label: "Try different keywords or browse categories above",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f111: {
    label: "Still have questions?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f112: {
    label:
      "Our team is here to help. Get personalized answers from construction e",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f113: {
    label: "Contact Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f114: {
    label: "Call ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("faq", defaults, meta);
export const schema = module.schema;
export default module;
