import { defineContent } from "../types";
export const defaults = {
  f001: "For Architects & Building Science Consultants | Ascent Group",
  f002: "Specialty envelope contractor for architects and building science professionals. EIFS, air barriers, rainscreen cladding — hygrothermal performance, ASHRAE 90.1 compliance, and spec-aligned execution.",
  f003: "For Design Professionals",
  f004: "A Contractor Who Speaks Building Science",
  f005: "We execute envelope and interior scopes to your design intent — with the hygrothermal awareness, air barrier detailing, and field testing your high-performance assemblies demand.",
  f006: "Building envelope installation detail",
  f007: "Request a Consultation",
  f008: "View Capabilities",
  f009: "Home",
  f010: "For Architects",
  f011: "Building Science Focus",
  f012: "Spec Compliance",
  f013: "Field Testing",
  f014: "Systems We Install & Restore",
  f015: "Our crews are trained on the product lines you specify — not just generic application. We understand manufacturer details, warranty requirements, approved substrates, and how each system performs within your wall assembly.",
  f016: "Building Science We Understand",
  f017: "Your specs are rooted in building science principles. We install with an understanding of why each layer matters — not just how it goes on.",
  f018: "Standards & Specifications We Work To",
  f019: "We're familiar with the codes, standards, and testing protocols referenced in your specifications.",
  f020: "How We Work With Design Teams",
  f021: "From spec review to commissioning, our process is built around your documentation requirements, building science objectives, and review milestones.",
  f022: "Typical Project Types",
  f023: "Scopes we regularly execute for architects, building science consultants, and envelope engineers.",
  f024: "Why Specify Ascent Group",
  f025: "What sets us apart when you're recommending a trade contractor to your client.",
  f026: "85% Self-Performed",
  f027: "Our crews execute the work — no sub-tiers diluting quality or accountability on your project.",
  f028: "WSIB & $2M CGL",
  f029: "Fully compliant, fully insured. Prequalification package available on request for your client's procurement team.",
  f030: "Spec-Aligned Execution",
  f031: "We read your specs before we price. Submittals, mock-ups, and warranty docs delivered to your schedule.",
  f032: "Common Questions from Design Teams",
  f033: "Hygrothermal modeling, ASTM testing, submittals, and spec compliance — covered.",
  f034: "Have a Project Coming to Tender?",
  f035: "Send us the scope and we'll provide unit pricing, a capability statement, and references for similar completed work.",
  f036: "Or call us directly: ",
  f037: "Request a Consultation",
  f038: "View Prequalification Package",
  f039: "Resources for Design Teams",
  f040: "Capabilities Statement",
  f041: "Self-perform crew, project sizes, delivery models, and operational standards in one capability brief.",
  f042: "Prequalification Documents",
  f043: "Insurance, WSIB, safety policy, and references — packaged for your client's procurement team.",
  f044: "Building Envelope Services",
  f045: "EIFS, masonry, sealants, cladding, and waterproofing — full envelope and restoration scope detail.",
  f046: "EIFS & Stucco Systems",
  f047: "Drainage cavity and barrier EIFS (Dryvit, Sto, Finestone). Continuous insulation achieving effective R-values per ASHRAE 90.1 and OBC SB-10. Proper drainage mat detailing, base coat reinforcement, and moisture management at penetrations and transitions.",
  f048: "Masonry & Stone",
  f049: "Tuckpointing, brick replacement, lintel repair, and stone restoration. CSA A371-compliant mortar matching for vapor permeability and freeze-thaw resistance. Heritage-sensitive repointing with compatible mortar profiles and aggregate matching.",
  f050: "Cladding & Rainscreen",
  f051: "Pressure-equalized rainscreen systems in ACM, fiber cement, metal panel, and composite cladding. Ventilated cavity design with thermal break fasteners to minimize thermal bridging. Engineered attachment through continuous insulation per manufacturer load tables.",
  f052: "Protective Coatings",
  f053: "Elastomeric wall coatings with specified permeance ratings (perms) to maintain vapor-open assemblies. Anti-carbonation treatments for concrete, parking deck traffic membranes, and high-elongation systems for crack-bridging on dynamic substrates.",
  f054: "Waterproofing & Sealants",
  f055: "Hydrostatic and non-hydrostatic membrane systems. Below-grade waterproofing, traffic deck assemblies, and joint sealant replacement programs. Class I, II, and III vapor retarder selection per assembly dew point analysis. Testing per ASTM D4263 and ASTM E96.",
  f056: "Interior Finishing",
  f057: "Fire-rated wall and ceiling assemblies (ULC-listed). Level 5 drywall finish for critical light conditions. Acoustic assemblies achieving specified STC/IIC ratings. Precision finishing for tenant improvements and suite turnovers.",
  f058: "Hygrothermal Performance",
  f059: "We understand vapor drive direction, dew point location within assemblies, and condensation risk. Our detailing supports your WUFI modeling assumptions — ensuring the as-built assembly performs as designed through heating and cooling seasons.",
  f060: "Air Barrier Continuity",
  f061: "Whole-building air tightness depends on transition details at slab edges, window-to-wall interfaces, and roof-to-wall junctions. We install and detail air barrier systems (self-adhered, fluid-applied, mechanical) with continuity verified through blower door coordination.",
  f062: "Thermal Bridging",
  f063: "We understand the difference between nominal and effective R-value. Our crews install thermally broken cladding attachments, insulated shelf angle details, and continuous insulation strategies that maintain the thermal performance your energy model requires.",
  f064: "Moisture Management",
  f065: "Drainage plane continuity, kick-out flashing integration, through-wall flashing at shelf angles, weep systems in masonry veneer, and capillary breaks at grade transitions. Every layer is sequenced to shed water outward.",
  f066: "Ontario energy efficiency requirements",
  f067: "Energy standard for buildings",
  f068: "Ventilation for acceptable IAQ",
  f069: "Masonry construction for buildings",
  f070: "Concrete materials and construction",
  f071: "Field water penetration testing",
  f072: "Air leakage of building materials",
  f073: "Thermal performance of assemblies",
  f074: "EIFS system evaluations",
  f075: "Air barrier certified installation details",
  f076: "Specification & Constructability Review",
  f077: "We review your drawings, specs, and envelope details to confirm scope, identify constructability concerns around thermal and moisture continuity, and flag product substitution opportunities that maintain design intent.",
  f078: "Shop Drawings, Submittals & Analysis Coordination",
  f079: "Detailed shop drawings, product data sheets, and material samples prepared to your format and timeline. We coordinate with your building science consultant on WUFI analysis assumptions and thermal modeling inputs.",
  f080: "Mock-Up, Testing & Approval",
  f081: "On-site mock-ups for envelope assemblies, coating systems, or finish samples. Field air and water penetration testing per ASTM E1105 and AAMA 501.2, coordinated with your field review schedule.",
  f082: "Execution, Commissioning & Closeout",
  f083: "Self-performed installation by trained crews. Thermographic scanning documentation, warranty packages, as-built records, and maintenance guides. Commissioning support for air barrier and envelope performance verification.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 600,
    locked: false,
  },
  f003: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 534,
    locked: false,
  },
  f006: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 666,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f016: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 417,
    locked: false,
  },
  f018: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 441,
    locked: false,
  },
  f022: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "85% Self-Performed",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f027: {
    label:
      "Our crews execute the work — no sub-tiers diluting quality or accounta",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "WSIB & $2M CGL",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f029: {
    label:
      "Fully compliant, fully insured. Prequalification package available on ",
    section: "Page copy",
    kind: "text",
    maxLength: 339,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f030: {
    label: "Spec-Aligned Execution",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label:
      "We read your specs before we price. Submittals, mock-ups, and warranty",
    section: "Page copy",
    kind: "text",
    maxLength: 309,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f032: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "Have a Project Coming to Tender?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label:
      "Send us the scope and we'll provide unit pricing, a capability stateme",
    section: "Page copy",
    kind: "text",
    maxLength: 348,
    locked: false,
  },
  f036: {
    label: "Or call us directly: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "Request a Consultation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "View Prequalification Package",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 303,
    locked: false,
  },
  f042: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f044: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 759,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f048: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 726,
    locked: false,
  },
  f050: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 786,
    locked: false,
  },
  f052: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 735,
    locked: false,
  },
  f054: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 771,
    locked: false,
  },
  f056: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 684,
    locked: false,
  },
  f058: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 726,
    locked: false,
  },
  f060: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 813,
    locked: false,
  },
  f062: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 774,
    locked: false,
  },
  f064: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 657,
    locked: false,
  },
  f066: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f076: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 654,
    locked: false,
  },
  f078: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 639,
    locked: false,
  },
  f080: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 579,
    locked: false,
  },
  f082: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f083: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 663,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("for-architects", defaults, meta);
export const schema = module.schema;
export default module;
