import { defineContent } from "../types";
export const defaults = {
  f001: "Façade remediation and cladding repairs",
  f002: "EIFS / stucco installation and repair",
  f003: "Sealant (caulking) replacement programs",
  f004: "Masonry restoration and tuckpointing",
  f005: "Balcony waterproofing systems",
  f006: "Protective coatings (interior/exterior)",
  f007: "Commercial and residential painting",
  f008: "Tile and flooring installation",
  f009: "Interior finishing and buildouts",
  f010: "48-Hour Quote Turnaround",
  f011: "Unit pricing for envelope scope on active tenders—typical response within 2 business days for standard packages",
  f012: "Self-Performed Work (85%)",
  f013: "10-person dedicated crew handles EIFS, masonry, sealant, painting—minimal sub-tiers, direct accountability on every project",
  f014: "WSIB & $2M CGL Coverage",
  f015: "Active WSIB registration since incorporation, comprehensive general liability, verified site safety protocols",
  f016: "Daily Progress Reporting",
  f017: "Dedicated project lead assigned to every job—daily photo updates, prompt RFI turnaround within 24 hours",
  f018: "Manufacturer-Compliant Documentation",
  f019: "Complete closeout packages with product data sheets, warranty certificates, and material compliance verification",
  f020: "Envelope & Interior Focus Only",
  f021: "We bid what we execute well—no structural, mechanical, or electrical scope creep",
  f022: "Tender Review & Clarifications",
  f023: "We review your bid package, confirm scope boundaries, and submit RFIs for any ambiguities—ensuring accurate pricing without hidden assumptions",
  f024: "Competitive Unit Rate Submission",
  f025: "Detailed pricing by trade and activity within 48 hours for standard packages—broken down for transparency and easy comparison",
  f026: "Pre-Start Coordination",
  f027: "Upon award, we coordinate directly with your site superintendent for access, safety protocols, material deliveries, and schedule integration",
  f028: "Daily Execution & Reporting",
  f029: "Dedicated project lead provides daily photo updates, tracks progress against schedule, and responds to RFIs within 24 hours",
  f030: "Closeout & Documentation",
  f031: "Final walkthrough with deficiency list, product data sheets, warranty certificates, and material compliance documentation delivered digitally",
  f032: "Trade Partner for General Contractors",
  f033: "Ascent Group provides building envelope and interior trade services as a reliable subcontractor partner for general contractors across Ontario. Fast quotes, self-performed work, and professional execution.",
  f034: "Reliable Trade Partner for General Contractors",
  f035: "Subcontractor services for building envelope and interior trades. Self-performed work, fast quotes, professional execution. Serving GCs across commercial, multi-family, and institutional projects.",
  f036: "Construction management for general contractors",
  f037: "Home",
  f038: "For General Contractors",
  f039: "Trade Packages We Execute",
  f040: "Specialized envelope and interior trades for commercial, multi-family, and institutional projects",
  f041: "Typical Project Scope:",
  f042: "Trade package values: $25k - $75k+ | Mid-rise to high-rise projects (5-30 storeys) | New construction and occupied building restoration",
  f043: "Why GCs Choose Ascent Group",
  f044: "Reliable envelope and interior trades partner—built on professional execution and direct accountability",
  f045: "Our Process for GC Partners",
  f046: "From tender review to project closeout—clear steps for seamless collaboration",
  f047: "Credentialed & Ready to Quote",
  f048: "Our team brings 15+ years of combined building envelope and interior trades experience from GTA commercial and multi-family projects. We're incorporated in Ontario, fully insured, and actively bidding on commercial and institutional scopes.",
  f049: "15+ years team experience",
  f050: "Highrise and commercial project background across the GTA",
  f051: "Active on bidding platforms",
  f052: "DataBid, ConstructConnect, and more",
  f053: "WSIB compliant",
  f054: "Active clearance with comprehensive site safety protocols",
  f055: "$2M CGL coverage",
  f056: "Comprehensive liability insurance, certificates on request",
  f057: "References available",
  f058: "Team-level references from prior project experience",
  f059: "Competitive, transparent pricing",
  f060: "Unit rates broken down for easy review and comparison",
  f061: "We're focused on building long-term relationships with GC partners through professional execution, clear communication, and reliable follow-through on every project we take on.",
  f062: "Prequalification Documents",
  f063: "Download our complete prequalification package including:",
  f064: "Company profile and project experience",
  f065: "WSIB clearance certificate",
  f066: "Insurance certificates ($2M CGL coverage)",
  f067: "Safety certifications and COR training records",
  f068: "Sample project references and past performance",
  f069: "Access Documents",
  f070: "What We Bring to Your Project",
  f071: "Operational capabilities that matter on-site",
  f072: "Work With Us",
  f073: "Add us to your bidders list or request unit pricing on active tenders",
  f074: "Call Us",
  f075: "Request Unit Pricing",
  f076: "Send us your tender package for competitive pricing",
  f077: "Submit Tender Request",
  f078: "Contact for Tendering:",
  f079: "Common Questions from General Contractors",
  f080: "Bid turnaround, prequalification, daily reporting, and self-perform scope — all answered.",
  f081: "More for GC Partners",
  f082: "Prequalification Package",
  f083: "Insurance, WSIB, safety, and references — assembled for procurement teams in one downloadable package.",
  f084: "Capabilities & Self-Perform",
  f085: "How we structure self-performed envelope and finish trades on commercial and multi-family GC projects.",
  f086: "Emergency Response",
  f087: "Same-day envelope and water-infiltration response for active project issues across the GTA.",
};
export const meta = {
  f001: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f011: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 333,
    locked: false,
  },
  f012: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f013: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 369,
    locked: true,
  },
  f014: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f015: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 327,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f016: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 309,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f018: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f020: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 426,
    locked: false,
  },
  f024: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 375,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f026: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 420,
    locked: false,
  },
  f028: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 369,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f030: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 423,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f032: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 615,
    locked: false,
  },
  f034: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 588,
    locked: false,
  },
  f036: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Typical Project Scope:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label:
      "Trade package values: $25k - $75k+ | Mid-rise to high-rise projects (5",
    section: "Page copy",
    kind: "text",
    maxLength: 405,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 309,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "Credentialed & Ready to Quote",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label:
      "Our team brings 15+ years of combined building envelope and interior t",
    section: "Page copy",
    kind: "text",
    maxLength: 720,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f049: {
    label: "15+ years team experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Highrise and commercial project background across the GTA",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Active on bidding platforms",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "DataBid, ConstructConnect, and more",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "WSIB compliant",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f054: {
    label: "Active clearance with comprehensive site safety protocols",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "$2M CGL coverage",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f056: {
    label: "Comprehensive liability insurance, certificates on request",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f057: {
    label: "References available",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "Team-level references from prior project experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "Competitive, transparent pricing",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Unit rates broken down for easy review and comparison",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label:
      "We're focused on building long-term relationships with GC partners thr",
    section: "Page copy",
    kind: "text",
    maxLength: 528,
    locked: false,
  },
  f062: {
    label: "Prequalification Documents",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "Download our complete prequalification package including:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "Company profile and project experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "WSIB clearance certificate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f066: {
    label: "Insurance certificates ($2M CGL coverage)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f067: {
    label: "Safety certifications and COR training records",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f068: {
    label: "Sample project references and past performance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "Access Documents",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "Call Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "Request Unit Pricing",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "Send us your tender package for competitive pricing",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label: "Submit Tender Request",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "Contact for Tendering:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f083: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 306,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f084: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 306,
    locked: false,
  },
  f086: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("for-general-contractors", defaults, meta);
export const schema = module.schema;
export default module;
