import { defineContent } from "../types";
export const defaults = {
  f001: "About Ascent Group",
  f002: "Building Envelope, Restoration & Interior Trades Across Toronto (GTA)",
  f003: "Lead contractor for envelope restoration, interior buildouts, painting, and specialty trades — planning, self-performing, and delivering accountable results across the GTA and Golden Horseshoe.",
  f004: "Ascent Group Construction protects and improves buildings — from exterior envelope and ",
  f005: "façade restoration",
  f006: "interior buildouts",
  f007: "painting",
  f008: ", and finishing trades. We act as the lead contractor, planning access and safety, self-performing the core trades, and communicating clearly from site walk to closeout.",
  f009: "Our foundation is building envelope — but our capability extends across the full scope of restoration, interior construction, and specialty trades that commercial and multi-unit properties require.",
  f010: "We self-perform key trades —",
  f011: "sealants/caulking, EIFS & stucco, masonry repairs and tuckpointing, waterproofing & protective coatings, concrete and parking-garage rehabilitation, commercial painting, interior buildouts, and tile & flooring",
  f012: "— coordinating trusted partners only when needed.",
  f013: "We work safely in occupied buildings, document progress with photo logs, and provide applicable manufacturer and workmanship warranties.",
  f014: "Toronto · Mississauga · Brampton · Vaughan · Markham · GTA & Golden Horseshoe",
  f015: "48–72 hour response on new enquiries",
  f016: "Our Services",
  f017: "Specialty Trades, Self-Performed",
  f018: "Eight core service lines delivered by our own trained crews — no sub-contractor hand-offs, full accountability on every project.",
  f019: "Learn more about ",
  f020: "View all services",
  f021: "Façade Remediation",
  f022: "Sealant replacement, panel repairs, and full building envelope restoration.",
  f023: "Full-scope envelope rehabilitation: condition assessments, sealant removal and replacement, panel re-anchoring, flashing repairs, and waterproof membrane integration. We coordinate swing-stage access and occupied-building logistics so tenants aren't disrupted.",
  f024: "EIFS & Stucco Systems",
  f025: "Energy-efficient insulated finish systems and traditional stucco repair.",
  f026: "New EIFS installation and existing system rehabilitation — base-coat repairs, mesh replacement, finish-coat colour matching, and drainage-plane corrections. Installed per manufacturer specs for warranty-eligible assemblies.",
  f027: "Masonry Restoration",
  f028: "Repointing, tuckpointing, and structural stabilisation for brick and stone.",
  f029: "Mortar analysis and compatible repointing, crack stitching, lintel replacement, stone dutchman repairs, and through-wall flashing installation. Heritage-sensitive methods available for designated properties.",
  f030: "Waterproofing",
  f031: "Below-grade, foundation, and deck waterproofing to stop water at the source.",
  f032: "Blind-side, positive-side, and negative-side waterproofing systems. Traffic-bearing membranes for plaza decks, foundation damp-proofing, crack injection, and drainage board installation.",
  f033: "Metal Cladding",
  f034: "Aluminum, steel, and composite panel installation and repairs.",
  f035: "ACM, MCM, and solid-aluminum panel systems — sub-girt layout, panel fabrication coordination, thermal-break detailing, and integration with air/vapour barriers for complete rain-screen assemblies.",
  f036: "Parking Garage Restoration",
  f037: "Concrete repair, traffic coatings, and structural rehab for parkades.",
  f038: "Condition surveys, concrete delamination removal, rebar treatment, shotcrete/form-and-pour repairs, expansion joint replacement, and traffic-bearing polyurethane or MMA coating systems.",
  f039: "Interior Buildouts",
  f040: "Tenant improvements, suite builds, drywall, and finishing trades.",
  f041: "Demising walls, ceiling grids, suite finishing, millwork coordination, and final paint. We handle permit-ready layouts through to deficiency-free handover for commercial and multi-residential interiors.",
  f042: "Commercial Painting",
  f043: "Commercial, condo, and multi-unit painting with premium coatings.",
  f044: "Surface prep, primer systems, and premium finish coats from Benjamin Moore and Sherwin-Williams. Common-area refresh programs, suite turnovers, and high-performance coatings for parking and mechanical rooms.",
  f045: "Complete Services",
  f046: "Lead specialty contractor with self-perform trades delivering schedule certainty and quality control across envelope, restoration, painting, and interior projects.",
  f047: "Building Our Track Record",
  f048: "15+ years combined team experience with on-time, on-budget delivery serving developers, property managers, and institutional clients across the Greater Toronto Area.",
  f049: "Building Our Credentials",
  f050: "Licensed business with WSIB registration and insurance in progress. Committed to safety, quality documentation, and professional execution on every project.",
};
export const meta = {
  f001: {
    label: "About Ascent Group",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label:
      "Building Envelope, Restoration & Interior Trades Across Toronto (GTA)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label:
      "Lead contractor for envelope restoration, interior buildouts, painting",
    section: "Page copy",
    kind: "text",
    maxLength: 579,
    locked: false,
  },
  f004: {
    label:
      "Ascent Group Construction protects and improves buildings — from exter",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "façade restoration",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "interior buildouts",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "painting",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label:
      ", and finishing trades. We act as the lead contractor, planning access",
    section: "Page copy",
    kind: "text",
    maxLength: 507,
    locked: false,
  },
  f009: {
    label:
      "Our foundation is building envelope — but our capability extends acros",
    section: "Page copy",
    kind: "text",
    maxLength: 591,
    locked: false,
  },
  f010: {
    label: "We self-perform key trades —",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label:
      "sealants/caulking, EIFS & stucco, masonry repairs and tuckpointing, wa",
    section: "Page copy",
    kind: "text",
    maxLength: 627,
    locked: false,
  },
  f012: {
    label: "— coordinating trusted partners only when needed.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label:
      "We work safely in occupied buildings, document progress with photo log",
    section: "Page copy",
    kind: "text",
    maxLength: 408,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f014: {
    label:
      "Toronto · Mississauga · Brampton · Vaughan · Markham · GTA & Golden Ho",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "48–72 hour response on new enquiries",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f016: {
    label: "Our Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Specialty Trades, Self-Performed",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label:
      "Eight core service lines delivered by our own trained crews — no sub-c",
    section: "Page copy",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f019: {
    label: "Learn more about ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "View all services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 780,
    locked: false,
  },
  f024: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 669,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f027: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 621,
    locked: false,
  },
  f030: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 558,
    locked: false,
  },
  f033: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 588,
    locked: false,
  },
  f036: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 555,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 606,
    locked: false,
  },
  f042: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 621,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 489,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 495,
    locked: false,
  },
  f049: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 468,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("home-service-highlights", defaults, meta);
export const schema = module.schema;
export default module;
