import { defineContent } from "../types";
export const defaults = {
  f001: "Something went wrong",
  f002: "We couldn't send your request. Please try again or call us directly.",
  f003: "Your Envelope, Restoration & Trades Partner",
  f004: "From concept to completion, we deliver exceptional results with transparent communication and expert craftsmanship.",
  f005: "Fully Licensed",
  f006: "WSIB Compliant",
  f007: "Responsive Support",
  f008: "Request Received",
  f009: "Thanks — we'll reach out within 24 hours",
  f010: "at ",
  f011: "Submit another inquiry",
  f012: "View our work",
  f013: "Start a Project Conversation",
  f014: "Scope review and pricing within 48 hours. No obligation.",
  f015: "Company website (leave blank)",
  f017: "Your full name",
  f019: "Email address",
  f021: "Phone number",
  f023: "Project description",
  f025: "Submit Inquiry",
  f026: "Prefer to talk directly?",
  f027: "Email Us",
  f028: "Years Team Experience",
  f029: "Our crew brings hands-on experience from envelope, restoration, and interior trades projects across the GTA.",
  f030: "Self-Performed Work",
  f031: "New company. Experienced team. Building trust project by project.",
  f032: "CGL Coverage",
  f033: "Fully insured with comprehensive liability coverage on every project.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "Your Envelope, Restoration & Trades Partner",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label:
      "From concept to completion, we deliver exceptional results with transp",
    section: "Page copy",
    kind: "text",
    maxLength: 345,
    locked: false,
  },
  f005: {
    label: "Fully Licensed",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "WSIB Compliant",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f007: {
    label: "Responsive Support",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "Request Received",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "Thanks — we'll reach out within 24 hours",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f010: {
    label: "at ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "Submit another inquiry",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "View our work",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "Start a Project Conversation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "Scope review and pricing within 48 hours. No obligation.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f015: {
    label: "Company website (leave blank)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Your full name",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Email address",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Phone number",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Project description",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Submit Inquiry",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Prefer to talk directly?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Email Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 324,
    locked: false,
  },
  f030: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f033: {
    label: "detail",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("home-inquiry", defaults, meta);
export const schema = module.schema;
export default module;
