import { defineContent } from "../types";
export const defaults = {
  f001: "Interior & Exterior Painting",
  f002: "Complete painting services for homes, condos, and townhouses. Professional prep work, quality finishes, and clean execution.",
  f003: "Full interior painting (walls, ceilings, trim)",
  f004: "Exterior painting (siding, stucco, brick)",
  f005: "Color consultation and matching",
  f006: "Minor drywall repair included",
  f007: "Stucco & EIFS Repair",
  f008: "Residential stucco repairs, EIFS damage correction, and color-matched finishing. We fix cracks, water damage, and impact damage.",
  f009: "Stucco crack repair and patching",
  f010: "EIFS impact damage restoration",
  f011: "Water damage investigation and repair",
  f012: "Color and texture matching",
  f013: "Tile & Flooring Installation",
  f014: "Ceramic, porcelain, vinyl plank, and laminate installation for kitchens, bathrooms, basements, and living areas.",
  f015: "Tile installation (floor and wall)",
  f016: "Vinyl plank and laminate flooring",
  f017: "Bathroom and kitchen backsplashes",
  f018: "Subfloor prep and leveling",
  f019: "Waterproofing & Caulking",
  f020: "Residential waterproofing for basements, balconies, and building perimeter. Caulking replacement for windows and doors.",
  f021: "Window and door caulking replacement",
  f022: "Balcony waterproofing (condo units)",
  f023: "Basement waterproofing (interior/exterior)",
  f024: "Foundation crack repair",
  f025: "Renovation & Finishing",
  f026: "Basement finishing, bathroom renovations, kitchen updates, and general home improvements.",
  f027: "Basement finishing and drywall",
  f028: "Bathroom renovation and tiling",
  f029: "Kitchen backsplash and painting",
  f030: "Trim, doors, and finishing carpentry",
  f031: "Exterior Cladding & Siding",
  f032: "Siding repair and replacement for residential homes. Hardie board, vinyl, and wood siding services.",
  f033: "Siding repair and replacement",
  f034: "Hardie board installation",
  f035: "Trim and soffit work",
  f036: "Color-matched finishing",
  f037: "Fully Insured & WSIB Compliant",
  f038: "$2M CGL liability coverage and full WSIB compliance protect you and your property.",
  f039: "15+ Years Team Experience",
  f040: "Our crew brings hands-on experience from a wide range of residential and commercial projects across the GTA.",
  f041: "Clear Quotes, No Surprises",
  f042: "Detailed written estimates with itemized pricing. You know exactly what you're paying for.",
  f043: "On-Time, Professional Execution",
  f044: "We show up when we say we will, work efficiently, and clean up thoroughly every day.",
  f045: "Request an Estimate",
  f046: "Fill out our estimate form or call us directly. Describe your project and upload photos if available.",
  f047: "Site Visit & Estimate",
  f048: "We'll visit your home to assess the work, take measurements, and answer your questions. You'll receive a detailed written estimate within 2-3 days.",
  f049: "Schedule & Execute",
  f050: "Once you approve the estimate, we'll schedule your project (typically 1-3 weeks out). We arrive on time, work cleanly, and communicate throughout.",
  f051: "Final Walkthrough",
  f052: "We'll walk through the completed work with you, address any concerns, and provide care instructions and warranty information.",
  f053: "Residential Services for Homeowners | Painting, Renovations, Tile, Flooring | Ascent Group Construction",
  f054: "Professional residential construction services in Toronto and the GTA. Interior/exterior painting, stucco repair, tile & flooring, renovations, waterproofing. 15+ years experience, fully insured. Serving Toronto & GTA.",
  f055: "Residential Services for Homeowners",
  f056: "Professional Painting, Renovations, Tile, Flooring & More • 15+ Years Experience • Fully Insured • Serving Toronto & GTA",
  f057: "Quality home improvement services",
  f058: "Home",
  f059: "Homeowners",
  f060: "Owner-Operated",
  f061: "Fully Insured",
  f062: "Free Estimates",
  f063: "Trusted by Homeowners Across the GTA",
  f064: "Quality Construction Services for Your Home",
  f065: "Whether you're looking to refresh your home with new paint, repair exterior stucco damage, renovate your bathroom, or install new tile and flooring—we bring ",
  f066: "15+ years of professional construction experience",
  f067: "to residential projects across Toronto and the Greater Toronto Area.",
  f068: "We're a small, owner-operated team that delivers the same professional standards, quality materials, and clean execution you'd expect from larger firms—with the personalized attention and clear communication you deserve as a homeowner.",
  f069: "Our Residential Services",
  f070: "From simple repairs to complete renovations, we handle a wide range of residential construction services with professional execution and fair pricing.",
  f071: "Typical Scope:",
  f072: "Note:",
  f073: "Costs and timelines are estimates based on typical residential projects. Your actual project will be priced after a site visit.",
  f074: "Request an Estimate",
  f075: "How It Works",
  f076: "We've made it simple to get started. Here's what you can expect when working with Ascent Group Construction.",
  f077: "Common Questions from Homeowners",
  f078: "Everything you need to know before getting started",
  f079: "Ready to Start Your Home Project?",
  f080: "Get a detailed estimate in 2-3 days. No pressure, no obligation—just professional advice and transparent pricing.",
  f081: "Request an Estimate",
  f082: "Contact Us",
  f083: "Explore More for Homeowners",
  f084: "Painting & Finishes",
  f085: "Interior and exterior painting, color matching, and clean execution backed by professional crews.",
  f086: "Tile & Flooring",
  f087: "Ceramic, porcelain, vinyl plank, and laminate installation for kitchens, bathrooms, and living spaces.",
  f088: "Renovations & Buildouts",
  f089: "Basement finishing, bathroom updates, and full interior renovation scopes for residential properties.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 372,
    locked: false,
  },
  f003: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f009: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: false,
  },
  f015: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 357,
    locked: false,
  },
  f021: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f038: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 324,
    locked: false,
  },
  f041: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 303,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 441,
    locked: false,
  },
  f049: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 438,
    locked: false,
  },
  f051: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 375,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f053: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 309,
    locked: false,
  },
  f054: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 654,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 360,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f057: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f062: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "Trusted by Homeowners Across the GTA",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "Quality Construction Services for Your Home",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label:
      "Whether you're looking to refresh your home with new paint, repair ext",
    section: "Page copy",
    kind: "text",
    maxLength: 471,
    locked: false,
  },
  f066: {
    label: "15+ years of professional construction experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label:
      "to residential projects across Toronto and the Greater Toronto Area.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label:
      "We're a small, owner-operated team that delivers the same professional",
    section: "Page copy",
    kind: "text",
    maxLength: 705,
    locked: false,
  },
  f069: {
    label: "Our Residential Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label:
      "From simple repairs to complete renovations, we handle a wide range of",
    section: "Page copy",
    kind: "text",
    maxLength: 450,
    locked: false,
  },
  f071: {
    label: "Typical Scope:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "Note:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label:
      "Costs and timelines are estimates based on typical residential project",
    section: "Page copy",
    kind: "text",
    maxLength: 381,
    locked: false,
  },
  f074: {
    label: "Request an Estimate",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 324,
    locked: false,
  },
  f077: {
    label: "Common Questions from Homeowners",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "Everything you need to know before getting started",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 339,
    locked: false,
  },
  f081: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f083: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 306,
    locked: false,
  },
  f088: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 303,
    locked: false,
  },
} as const;
const module = defineContent("homeowners", defaults, meta);
export const schema = module.schema;
export default module;
