import { defineContent } from "../types";
export const defaults = {
  f001: "Why Choose Us",
  f002: "Why Clients Choose Us",
  f003: "Building performance is non‑negotiable—and ",
  f004: "accountability",
  f005: "is everything.",
  f006: "Developers, general contractors, property managers, and asset owners choose ",
  f007: "Ascent Group Construction",
  f008: "for specialized envelope, restoration, and ",
  f009: "interior trade delivery",
  f010: "across Toronto (GTA) and the Golden Horseshoe. We act as the ",
  f011: "lead contractor",
  f012: "—coordinating access and safety, ",
  f013: "self‑performing key trades",
  f014: ", and communicating clearly from ",
  f015: "site walk to closeout",
  f016: "We follow consultant/engineer‑of‑record (EOR) details, document work with ",
  f017: "photo logs/ITPs",
  f018: ", and provide ",
  f019: "applicable manufacturer and workmanship warranties",
  f020: "Request Site Assessment",
  f021: "View Services",
  f022: "For GCs: Request Unit Pricing",
  f023: "Who We Serve",
  f024: "From general contractors seeking reliable trade partners to property managers protecting their portfolios—we deliver specialized envelope, restoration, and interior trade solutions across Ontario and the GTA.",
  f025: "Prime accountability for project scopes",
  f026: "Self‑performed core trades",
  f027: "Consultant/EOR‑aligned execution",
  f028: "Documented QA/QC",
  f029: "Occupied‑building expertise",
  f030: "Responsive by design",
  f031: "Local coverage",
  f032: "General Contractors",
  f033: "Trade partner for envelope and restoration scopes on commercial and multi-family projects across the GTA.",
  f034: "Unit pricing for envelope packages",
  f035: "Fast RFP response (48-72 hours)",
  f036: "Self-performed core trades",
  f037: "Property Managers",
  f038: "Reliable envelope maintenance and emergency restoration for multi-residential and commercial portfolios.",
  f039: "10-30 story condominiums",
  f040: "Occupied building expertise",
  f041: "Clear documentation for reserve fund studies",
  f042: "Commercial Owners",
  f043: "Façade remediation and building envelope solutions for office buildings, retail strips, and industrial properties.",
  f044: "Water intrusion repairs",
  f045: "Parking garage restoration",
  f046: "Tenant coordination",
  f047: "Homeowners",
  f048: "Exterior restoration and interior renovation services for single-family homes across Ontario.",
  f049: "EIFS and stucco repair",
  f050: "Masonry restoration",
  f051: "Interior painting and finishes",
};
export const meta = {
  f001: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "Why Clients Choose Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "Building performance is non‑negotiable—and ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "accountability",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "is everything.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label:
      "Developers, general contractors, property managers, and asset owners c",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "for specialized envelope, restoration, and ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "interior trade delivery",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "across Toronto (GTA) and the Golden Horseshoe. We act as the ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "lead contractor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "—coordinating access and safety, ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "self‑performing key trades",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: ", and communicating clearly from ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "site walk to closeout",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label:
      "We follow consultant/engineer‑of‑record (EOR) details, document work w",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "photo logs/ITPs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: ", and provide ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "applicable manufacturer and workmanship warranties",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f020: {
    label: "Request Site Assessment",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "View Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "For GCs: Request Unit Pricing",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Who We Serve",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label:
      "From general contractors seeking reliable trade partners to property m",
    section: "Page copy",
    kind: "text",
    maxLength: 624,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 315,
    locked: false,
  },
  f034: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f036: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 312,
    locked: false,
  },
  f039: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 342,
    locked: false,
  },
  f044: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("home-audiences", defaults, meta);
export const schema = module.schema;
export default module;
