import { defineContent } from "../types";
export const defaults = {
  f001: "How to Choose a Reliable Construction Contractor in Ontario",
  f002: "A step-by-step guide to selecting a qualified construction contractor for your commercial or residential project",
  f003: "Verify Licensing and Insurance",
  f004: "Ensure the contractor has valid WSIB coverage, liability insurance, and necessary municipal licenses in Ontario",
  f005: "Check Experience and Portfolio",
  f006: "Review their portfolio of completed projects similar to yours, with a minimum of 10+ years industry experience",
  f007: "Request Multiple References",
  f008: "Contact at least 3 recent clients and verify project quality, timeline adherence, and communication",
  f009: "Compare Detailed Estimates",
  f010: "Get itemized quotes from 3+ contractors, comparing materials, timelines, and warranties",
  f011: "Review Contract Terms",
  f012: "Ensure written contracts include payment schedules, change order procedures, and completion guarantees",
  f013: "Why Choose Ascent Group Construction",
  f014: "Key reasons to choose Ascent Group Construction for your Toronto and GTA construction projects",
  f015: "Licensed Construction Excellence Across Ontario",
  f016: "Fully licensed and insured with $2M CGL liability coverage, active WSIB registration, working toward COR certification.",
  f017: "Specialty Trade Services",
  f018: "Envelope and interior trade services including masonry repair, EIFS installation, metal cladding, and parking garage restoration.",
  f019: "Premium Materials & Manufacturer Warranties",
  f020: "Benjamin Moore and Sherwin-Williams authorized contractor using premium materials backed by extended warranties.",
  f021: "Envelope & Restoration GTA",
  f022: "Specialty contractor in the GTA delivering façade remediation, waterproofing, EIFS, masonry & restoration. 15+ yrs crew, self-performed, WSIB, $2M CGL.",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: false,
  },
  f003: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f004: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 333,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f005: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 330,
    locked: false,
  },
  f007: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f011: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 306,
    locked: false,
  },
  f013: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 357,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f017: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 387,
    locked: false,
  },
  f019: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f020: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 336,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 453,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("home", defaults, meta);
export const schema = module.schema;
export default module;
