import { defineContent } from "../types";
export const defaults = {
  f001: "Home",
  f002: "Markets",
  f003: "Markets Served by Ascent Group Construction",
  f004: "Markets We Serve | Ascent Group Construction",
  f005: "Ascent Group Construction serves property managers, commercial clients, homeowners, developers, and general contractors across Ontario and the GTA.",
  f006: "Markets We Serve",
  f007: "Our Markets",
  f008: "Specialty construction services tailored to your sector — from property managers maintaining building envelopes to general contractors needing a reliable trade partner.",
  f009: "Markets served by Ascent Group Construction",
  f010: "Home",
  f011: "Markets",
  f012: "Multi-Sector Experience",
  f013: "Tailored Solutions",
  f014: "Trade Partnerships",
  f015: "Start a Project",
  f016: "Request Site Assessment",
  f017: "Who We Work With",
  f018: "Sector at a Glance",
  f019: "Sub-Sectors",
  f020: "FAQ",
  f021: "Who We Work With",
  f022: "From property managers maintaining building envelopes to general contractors needing a reliable trade partner, we deliver focused expertise to every client segment.",
  f023: "Sector at a Glance",
  f024: "Typical project size, decision-maker, and response cadence by client segment — so you know exactly how we engage.",
  f025: "Sector",
  f026: "Typical Scope",
  f027: "Decision-Maker",
  f028: "Response SLA",
  f029: "Common Services",
  f030: "Sub-Sectors We Serve",
  f031: "Across the five client segments above, we have direct experience in these property types.",
  f032: "People Also Ask",
  f033: "Quick answers to the most common questions about who we work with.",
  f034: "Property Managers",
  f035: "Building envelope maintenance, restoration programs, and capital improvement planning for multi-unit residential and commercial properties.",
  f036: "General Contractors",
  f037: "Reliable specialty trade partner for building envelope, interior finishing, and restoration scopes on commercial and institutional projects.",
  f038: "Commercial Clients",
  f039: "Exterior upgrades, tenant improvements, and façade systems for office, retail, and mixed-use commercial properties across the GTA.",
  f040: "Homeowners",
  f041: "Interior renovations, painting, tile and flooring, and exterior finishing for residential properties.",
  f042: "Developers",
  f043: "New construction finishing packages, multi-unit coordination, and phased completion schedules for residential and commercial developments.",
  f044: "Office",
  f045: "Retail",
  f046: "Hospitality",
  f047: "Healthcare",
  f048: "Education",
  f049: "Industrial",
  f050: "Multi-Residential",
  f051: "Mixed-Use",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 441,
    locked: false,
  },
  f006: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 504,
    locked: false,
  },
  f009: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 492,
    locked: false,
  },
  f023: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 339,
    locked: false,
  },
  f025: {
    label: "Sector",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Typical Scope",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Decision-Maker",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Response SLA",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Common Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 417,
    locked: false,
  },
  f036: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 420,
    locked: false,
  },
  f038: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 390,
    locked: false,
  },
  f040: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 303,
    locked: false,
  },
  f042: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 414,
    locked: false,
  },
  f044: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("markets", defaults, meta);
export const schema = module.schema;
export default module;
