import { defineContent } from "../types";
export const defaults = {
  f001: "How Ascent Group Construction Delivers Your Project",
  f002: "Our 7-step process from inquiry through post-project support ensures clear communication, quality execution, and complete documentation on every scope.",
  f003: "How We Work — From Inquiry to Closeout | Ascent Group Construction",
  f004: "Our 7-step process covers inquiry, site assessment, estimating, pre-construction, execution, closeout, and post-project support. Transparent communication and documentation at every stage.",
  f005: "How We Work",
  f006: "From Inquiry to Closeout",
  f007: "A clear, repeatable process for every project — transparent communication, documented progress, and accountability at every stage.",
  f008: "Ascent Group Construction project execution",
  f009: "Start a Project",
  f010: "Home",
  f011: "How We Work",
  f012: "Transparent Communication",
  f013: "Documented Progress",
  f014: "On-Time Delivery",
  f015: "Trust",
  f016: "7-Step Process",
  f017: "Related",
  f018: "FAQ",
  f020: "Active Registration",
  f022: "CGL Coverage",
  f023: "Years Team Experience",
  f024: "Self-Performed Work",
  f025: "7 Steps, Start to Finish",
  f026: "Every project follows this sequence — from initial scope review through warranty support",
  f027: "View Our Services",
  f028: "Building envelope, restoration, interior finishes, and specialty coatings — see the full scope of what we execute.",
  f029: "Explore Services ",
  f030: "See Our Project Work",
  f031: "Browse completed envelope, restoration, and interior projects across the GTA.",
  f032: "View Projects ",
  f033: "Pre-Qualification Docs",
  f034: "Download our capability statement, insurance certificates, and safety documentation.",
  f035: "View Pre-Qualification ",
  f036: "People Also Ask",
  f037: "Common questions about our project process and timelines.",
  f038: "Ready to Start a Project?",
  f039: "Request a consultation and detailed proposal. No pressure — just honest advice and transparent pricing.",
  f040: "Request a Quote",
  f041: "Contact Us",
  f042: "Inquiry & Scope Review",
  f043: "You reach out with a scope, RFP, or project question. We review requirements, confirm alignment with our capabilities, and respond with initial availability and trade relevance.",
  f044: "Review incoming RFP, tender, or scope documents",
  f045: "Confirm alignment with our trade capabilities (envelope, restoration, interior finishes)",
  f046: "Identify scope boundaries and flag any items outside our core trades",
  f047: "Respond with initial availability and next steps",
  f048: "Scope Confirmation",
  f049: "Initial Availability",
  f050: "Next Steps Outline",
  f051: "Site Assessment",
  f052: "We visit the site to assess conditions, measure surfaces, identify access constraints, and document existing conditions with photos and notes.",
  f053: "On-site inspection and condition assessment",
  f054: "Surface measurement and quantity takeoff",
  f055: "Access planning: scaffolding, swing stages, lifts, occupied-building constraints",
  f056: "Photo documentation of existing conditions",
  f057: "Identification of potential risks or coordination requirements",
  f058: "Site Photos",
  f059: "Condition Report",
  f060: "Access Plan",
  f061: "Estimate & Proposal",
  f062: "Detailed proposal with scope breakdown, material specifications, schedule options, and pricing. Line-item transparency, not lump-sum guesswork.",
  f063: "Line-item pricing by trade and activity",
  f064: "Material specifications and product data",
  f065: "Schedule options with milestone dates",
  f066: "Exclusions and assumptions clearly stated",
  f067: "Contract type recommendation (lump sum, unit price, T&M)",
  f068: "Detailed Proposal",
  f069: "Material Specs",
  f070: "Schedule Options",
  f071: "Pre-Construction Coordination",
  f072: "Scheduling, material procurement, access planning, safety documentation, and coordination with other trades or building operations.",
  f073: "Material procurement and lead-time management",
  f074: "Safety documentation: WSIB, site-specific safety plan, toolbox talks",
  f075: "Coordination with other trades, building management, or GC superintendent",
  f076: "Access scheduling: after-hours work, tenant notifications, phased approach",
  f077: "Mock-ups or samples for client approval (when applicable)",
  f078: "Safety Plan",
  f079: "Procurement Schedule",
  f080: "Coordination Plan",
  f081: "Execution & Reporting",
  f082: "Our crews mobilize with daily cleanup, progress photos, and weekly reporting. Direct communication with your project manager or site contact.",
  f083: "Crew mobilization with dedicated project lead",
  f084: "Daily progress photos and site cleanup",
  f085: "Weekly written progress reports",
  f086: "Real-time issue resolution and change order tracking",
  f087: "Quality inspections at key milestones",
  f088: "Progress Photos",
  f089: "Weekly Reports",
  f090: "Quality Records",
  f091: "Closeout & Documentation",
  f092: "Final walkthrough, punch-list resolution, warranty documentation, as-built records, and lien releases.",
  f093: "Final walkthrough with client or GC representative",
  f094: "Punch-list creation and resolution",
  f095: "Warranty documentation and manufacturer certificates",
  f096: "Product data sheets and material compliance records",
  f097: "Lien releases and final invoicing",
  f098: "Punch List Resolution",
  f099: "Warranty Package",
  f100: "Closeout Binder",
  f101: "Post-Project Support",
  f102: "Warranty service, maintenance guidance, and availability for follow-up scopes. We stay responsive after the job is done.",
  f103: "Warranty service for deficiency claims",
  f104: "Maintenance guidance and care instructions",
  f105: "Priority scheduling for follow-up or recurring scopes",
  f106: "Availability for emergency response (active leaks, storm damage)",
  f107: "Warranty Service",
  f108: "Maintenance Guide",
  f109: "Priority Access",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 453,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 564,
    locked: false,
  },
  f005: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 390,
    locked: false,
  },
  f008: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f023: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f027: {
    label: "View Our Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label:
      "Building envelope, restoration, interior finishes, and specialty coati",
    section: "Page copy",
    kind: "text",
    maxLength: 342,
    locked: false,
  },
  f029: {
    label: "Explore Services ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "See Our Project Work",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label:
      "Browse completed envelope, restoration, and interior projects across t",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "View Projects ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Pre-Qualification Docs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label:
      "Download our capability statement, insurance certificates, and safety ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f035: {
    label: "View Pre-Qualification ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 309,
    locked: false,
  },
  f040: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 531,
    locked: false,
  },
  f044: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 426,
    locked: false,
  },
  f053: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 429,
    locked: false,
  },
  f063: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f070: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 393,
    locked: false,
  },
  f073: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f075: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 423,
    locked: false,
  },
  f083: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f086: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f090: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f091: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f092: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 306,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f093: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f094: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f095: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f096: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f097: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f098: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f099: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f100: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f101: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f102: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 360,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f103: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f104: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f105: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f106: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f107: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f108: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f109: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("our-process", defaults, meta);
export const schema = module.schema;
export default module;
