import { defineContent } from "../types";
export const defaults = {
  f001: "Vendor Pre-Qualification Package - Main Specialty Contractor | Ascent Group Construction",
  f002: "Pre-qualification package for Ascent Group Construction - 15+ years team experience in building envelope, EIFS, masonry, interior trades. WSIB compliant, $2M CGL coverage. Serving GCs, property managers, and building owners in Ontario.",
  f003: "Contractor Pre-Qualification",
  f004: "Vendor Pre-Qualification Package",
  f005: "15+ Years Combined Team Experience • Building Envelope & Interior Trades Specialist • WSIB Compliant • $2M CGL Coverage • Serving Commercial, Multi-Family & Residential Markets",
  f006: "Pre-qualification and certifications",
  f007: "Contact Us",
  f008: "How We Deliver",
  f009: "Home",
  f010: "Pre-Qualification",
  f011: "Company Status: New Incorporation, Experienced Team",
  f012: "Ascent Group Construction was incorporated in 2025, but our team brings ",
  f013: "15+ years of combined hands-on experience",
  f014: "from building envelope and interior trades work on commercial and multi-family projects throughout the Greater Toronto Area.",
  f015: "We founded Ascent Group to provide ",
  f016: "direct, accountable specialty trade execution",
  f017: "for property managers, building owners, consultants, and general contractors who need reliable partners for envelope restoration, waterproofing, EIFS, masonry, and interior finishing work.",
  f019: "Overview",
  f021: "Documents",
  f023: "Projects",
  f025: "Contact",
  f027: "Company Capabilities",
  f028: "Why Choose Ascent Group",
  f029: "Safety Excellence",
  f030: "Working toward COR certification with comprehensive safety protocols and training across all projects.",
  f031: "Quality Workmanship",
  f032: "ISO-compliant quality management systems. Every project backed by comprehensive warranties and guarantees.",
  f033: "Financial Stability",
  f034: "Strong credit references and financial documentation available upon request. Payment and performance bonds can be arranged through surety partners for projects requiring them.",
  f036: "Downloadable Documents",
  f037: "All required documentation for contractor pre-qualification and RFP submissions",
  f039: "Recent Project Performance",
  f040: "Representative projects demonstrating our capabilities and experience",
  f041: "Sector",
  f042: "Year",
  f043: "Project Value",
  f044: "View All Projects",
  f046: "Get in Touch",
  f047: "Phone",
  f048: "Email",
  f049: "Service Area",
  f050: "Greater Toronto Area",
  f051: "Submit Your RFP",
  f052: "We respond to all requests for proposals within 48 hours",
  f053: "Fast Response",
  f054: "48-hour turnaround",
  f055: "Detailed Proposals",
  f056: "Itemized estimates",
  f057: "Value Engineering",
  f058: "Cost optimization",
  f059: "Submit RFP Now",
  f060: "Or contact us directly",
  f061: "Ready to Work Together?",
  f062: "Contact our team to discuss your project scope, review our credentials, or request a detailed proposal.",
  f063: "Request a Quote",
  f064: "Contact Us",
  f065: "Team Experience",
  f067: "Company Status",
  f069: "Insurance Coverage",
  f071: "Safety Commitment",
  f073: "Project Range",
  f075: "Core Crew",
  f077: "Multi-Unit EIFS Repair",
  f079: "Commercial Storefront Renovation",
  f081: "Condo Balcony Waterproofing",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 705,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f003: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 528,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f006: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "Company Status: New Incorporation, Experienced Team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label:
      "Ascent Group Construction was incorporated in 2025, but our team bring",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
  },
  f013: {
    label: "15+ years of combined hands-on experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label:
      "from building envelope and interior trades work on commercial and mult",
    section: "Page copy",
    kind: "text",
    maxLength: 372,
    locked: false,
  },
  f015: {
    label: "We founded Ascent Group to provide ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "direct, accountable specialty trade execution",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label:
      "for property managers, building owners, consultants, and general contr",
    section: "Page copy",
    kind: "text",
    maxLength: 564,
    locked: false,
  },
  f019: {
    label: "Overview",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Documents",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Contact",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Company Capabilities",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Why Choose Ascent Group",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Safety Excellence",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label:
      "Working toward COR certification with comprehensive safety protocols a",
    section: "Page copy",
    kind: "text",
    maxLength: 306,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f031: {
    label: "Quality Workmanship",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label:
      "ISO-compliant quality management systems. Every project backed by comp",
    section: "Page copy",
    kind: "text",
    maxLength: 318,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f033: {
    label: "Financial Stability",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label:
      "Strong credit references and financial documentation available upon re",
    section: "Page copy",
    kind: "text",
    maxLength: 525,
    locked: false,
  },
  f036: {
    label: "Downloadable Documents",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label:
      "All required documentation for contractor pre-qualification and RFP su",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Recent Project Performance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label:
      "Representative projects demonstrating our capabilities and experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Sector",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "Year",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "Project Value",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "View All Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "Get in Touch",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "Phone",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "Email",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "Service Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Greater Toronto Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Submit Your RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "We respond to all requests for proposals within 48 hours",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f053: {
    label: "Fast Response",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "48-hour turnaround",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f055: {
    label: "Detailed Proposals",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "Itemized estimates",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "Value Engineering",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "Cost optimization",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label: "Submit RFP Now",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Or contact us directly",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 309,
    locked: false,
  },
  f063: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f065: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f071: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("prequalification", defaults, meta);
export const schema = module.schema;
export default module;
