import { defineContent } from "../types";
export const defaults = {
  f001: "Privacy Policy | Ascent Group Construction",
  f003: "Privacy policy for Ascent Group Construction - PIPEDA compliant information about how we collect, use, and protect your personal information.",
  f005: "index, follow",
  f006: "Privacy Policy",
  f007: "Last Updated: ",
  f008: "1. Introduction",
  f009: 'Ascent Group Construction ("we," "our," or "us") is committed to protecting your privacy and personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information in compliance with Canada\'s Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable provincial privacy laws.',
  f010: "By using our website or services, you consent to the collection and use of your information as described in this Privacy Policy.",
  f011: "2. What Personal Information We Collect",
  f012: "We collect the following types of personal information:",
  f013: "2.1 Information You Provide Directly",
  f014: "Contact Forms:",
  f015: "Name, email address, phone number, company name, and message content",
  f016: "Newsletter Subscriptions:",
  f017: "Email address, subscription preferences, consent timestamp",
  f018: "RFP/Estimate Requests:",
  f019: "Project details, timeline, budget information, contact information",
  f020: "Job Applications:",
  f021: "Name, email, phone, resume, cover letter, portfolio links",
  f022: "Prequalification Forms:",
  f023: "Company information, project requirements, contact details",
  f024: "2.2 Information Collected Automatically",
  f025: "Technical Data:",
  f026: "IP address, browser type, device information, operating system",
  f027: "Usage Data:",
  f028: "Pages visited, time spent on pages, click patterns, referral sources",
  f029: "Cookies:",
  f030: "Session cookies, analytics cookies (see Section 7 for details)",
  f031: "3. Why We Collect Your Information",
  f032: "We collect and use your personal information for the following purposes:",
  f033: "Respond to Inquiries:",
  f034: "To answer your questions and provide information about our services",
  f035: "Newsletter Communications:",
  f036: "To send industry insights, project updates, and company news (with your consent)",
  f037: "Project Proposals:",
  f038: "To prepare estimates, RFP responses, and project documentation",
  f039: "Job Applications:",
  f040: "To review qualifications and contact candidates",
  f041: "Website Improvement:",
  f042: "To analyze usage patterns and improve user experience",
  f043: "Legal Compliance:",
  f044: "To comply with applicable laws and regulations",
  f045: "Security:",
  f046: "To protect against fraud, unauthorized access, and abuse",
  f047: "4. How We Use Your Information",
  f048: "Your personal information is used internally for:",
  f049: "Processing and responding to your requests and communications",
  f050: "Sending newsletters and marketing communications (with consent)",
  f051: "Improving our website and services",
  f052: "Analyzing trends and user behavior",
  f053: "Maintaining security and preventing fraud",
  f054: "Complying with legal obligations",
  f055: "5. How Long We Keep Your Information",
  f056: "We retain personal information for the following periods:",
  f057: "Contact Form Inquiries:",
  f058: "2 years from submission date",
  f059: "Newsletter Subscriptions:",
  f060: "Until you unsubscribe or request deletion",
  f061: "Job Applications:",
  f062: "1 year from submission date",
  f063: "RFP/Estimate Requests:",
  f064: "3 years from project completion or proposal date",
  f065: "Analytics Data:",
  f066: "26 months (Google Analytics default)",
  f067: "Audit Logs:",
  f068: "7 years for legal and regulatory compliance",
  f069: "After the retention period expires, we securely delete or anonymize your information unless we are required by law to retain it longer.",
  f070: "6. Where Your Information is Stored",
  f071: "Your personal information is stored on secure servers located in Canada. We use Lovable Cloud (powered by Supabase) which maintains data centers in Canada and complies with Canadian data protection standards.",
  f072: "Some service providers (such as Google Analytics) may process data outside of Canada. When we transfer data internationally, we ensure appropriate safeguards are in place through standard contractual clauses and PIPEDA-compliant transfer mechanisms.",
  f073: "7. Who We Share Your Information With",
  f074: "We may share your personal information with:",
  f075: "7.1 Service Providers",
  f076: "Cloud Hosting:",
  f077: "Lovable Cloud/Supabase (data storage and processing)",
  f078: "Analytics:",
  f079: "Google Analytics (website usage analysis)",
  f080: "Email Services:",
  f081: "Resend (newsletter delivery)",
  f082: "7.2 Legal Requirements",
  f083: "We may disclose your information when required by law, such as:",
  f084: "In response to a court order, subpoena, or legal process",
  f085: "To comply with regulatory requirements (WSIB, CRA, etc.)",
  f086: "To protect our rights, property, or safety",
  f087: "To prevent fraud or illegal activity",
  f088: "7.3 Business Transfers",
  f089: "If we are involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction. We will notify you of any such change.",
  f090: "8. Cookies and Tracking Technologies",
  f091: "8.1 What Cookies We Use",
  f092: "Essential Cookies:",
  f093: "Required for website functionality (session management, security)",
  f094: "Analytics Cookies:",
  f095: "Google Analytics to understand how visitors use our site",
  f096: "Preference Cookies:",
  f097: "Remember your cookie consent choices",
  f098: "8.2 Why We Use Cookies",
  f099: "Ensure website security and functionality",
  f100: "Analyze site traffic and usage patterns",
  f101: "Improve user experience and website performance",
  f102: "Remember your preferences and settings",
  f103: "8.3 Managing Cookies",
  f104: "You can control cookies through:",
  f105: "Our cookie banner (shown on first visit)",
  f106: "Your browser settings (disable or delete cookies)",
  f107: "Google Analytics opt-out: ",
  f108: "Note: Disabling essential cookies may affect website functionality.",
  f109: "9. Your Privacy Rights",
  f110: "Under PIPEDA, you have the following rights regarding your personal information:",
  f111: "Right to Access:",
  f112: "Request a copy of the personal information we hold about you",
  f113: "Right to Correction:",
  f114: "Request correction of inaccurate or incomplete information",
  f115: "Right to Deletion:",
  f116: "Request deletion of your personal information (subject to legal retention requirements)",
  f117: "Right to Withdraw Consent:",
  f118: "Unsubscribe from newsletters or withdraw consent at any time",
  f119: "Right to Object:",
  f120: "Object to certain uses of your information",
  f121: "Right to Complain:",
  f122: "File a complaint with the Privacy Commissioner of Canada",
  f123: "How to Exercise Your Rights",
  f124: "To exercise any of these rights, contact us at:",
  f125: "Email:",
  f126: "Phone:",
  f127: "Mail:",
  f128: "Ascent Group Construction, Privacy Officer, 2 Jody Ave, North York, ON M3N 1H1",
  f129: "We will respond to your request within 30 days as required by PIPEDA.",
  f130: "10. How We Protect Your Information",
  f131: "We implement appropriate technical and organizational security measures to protect your personal information, including:",
  f132: "Encryption:",
  f133: "SSL/TLS encryption for data transmission",
  f134: "Access Controls:",
  f135: "Restricted access to personal information on a need-to-know basis",
  f136: "Secure Storage:",
  f137: "Encrypted database storage with regular backups",
  f138: "Security Monitoring:",
  f139: "Regular security audits and vulnerability assessments",
  f140: "Employee Training:",
  f141: "Staff trained on privacy and data protection practices",
  f142: "Breach Response:",
  f143: "Incident response plan to address potential data breaches",
  f144: "While we strive to protect your information, no method of transmission over the internet is 100% secure. We cannot guarantee absolute security.",
  f145: "11. Children's Privacy",
  f146: "Our website and services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If you believe we have collected information from a child, please contact us immediately, and we will delete the information.",
  f147: "12. Changes to This Privacy Policy",
  f148: 'We may update this Privacy Policy periodically to reflect changes in our practices, technology, legal requirements, or for other operational reasons. We will post the updated policy on this page with a new "Last Updated" date.',
  f149: "Material changes will be communicated through a prominent notice on our website or via email to newsletter subscribers. Your continued use of our website after changes constitutes acceptance of the updated policy.",
  f150: "13. Contact Information",
  f151: "Privacy Officer",
  f152: "For questions, concerns, or requests regarding this Privacy Policy or your personal information:",
  f153: "Ascent Group Construction",
  f154: "Privacy Officer",
  f155: "Email: ",
  f156: "Phone: ",
  f157: "If you are not satisfied with our response, you may file a complaint with the Office of the Privacy Commissioner of Canada: ",
  f158: "www.priv.gc.ca",
  f159: "14. PIPEDA Compliance Statement",
  f160: "This Privacy Policy has been designed to comply with Canada's Personal Information Protection and Electronic Documents Act (PIPEDA) and the ten principles of fair information practices. We are committed to protecting your privacy rights and maintaining transparency in our data handling practices.",
};
export const meta = {
  f001: {
    label: "Privacy Policy | Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 423,
    locked: false,
  },
  f005: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "Privacy Policy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "Last Updated: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "1. Introduction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label:
      'Ascent Group Construction ("we," "our," or "us") is committed to prote',
    section: "Page copy",
    kind: "text",
    maxLength: 1029,
    locked: false,
  },
  f010: {
    label:
      "By using our website or services, you consent to the collection and us",
    section: "Page copy",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f011: {
    label: "2. What Personal Information We Collect",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "We collect the following types of personal information:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "2.1 Information You Provide Directly",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "Contact Forms:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label:
      "Name, email address, phone number, company name, and message content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Newsletter Subscriptions:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Email address, subscription preferences, consent timestamp",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "RFP/Estimate Requests:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Project details, timeline, budget information, contact information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Job Applications:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Name, email, phone, resume, cover letter, portfolio links",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "Prequalification Forms:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Company information, project requirements, contact details",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "2.2 Information Collected Automatically",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Technical Data:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "IP address, browser type, device information, operating system",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Usage Data:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label:
      "Pages visited, time spent on pages, click patterns, referral sources",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Cookies:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "Session cookies, analytics cookies (see Section 7 for details)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "3. Why We Collect Your Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label:
      "We collect and use your personal information for the following purpose",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "Respond to Inquiries:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label:
      "To answer your questions and provide information about our services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "Newsletter Communications:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label:
      "To send industry insights, project updates, and company news (with you",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "Project Proposals:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "To prepare estimates, RFP responses, and project documentation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Job Applications:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "To review qualifications and contact candidates",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "Website Improvement:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "To analyze usage patterns and improve user experience",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "Legal Compliance:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "To comply with applicable laws and regulations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "Security:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "To protect against fraud, unauthorized access, and abuse",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "4. How We Use Your Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "Your personal information is used internally for:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "Processing and responding to your requests and communications",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Sending newsletters and marketing communications (with consent)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Improving our website and services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "Analyzing trends and user behavior",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "Maintaining security and preventing fraud",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "Complying with legal obligations",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "5. How Long We Keep Your Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "We retain personal information for the following periods:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f057: {
    label: "Contact Form Inquiries:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "2 years from submission date",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f059: {
    label: "Newsletter Subscriptions:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Until you unsubscribe or request deletion",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label: "Job Applications:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f062: {
    label: "1 year from submission date",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f063: {
    label: "RFP/Estimate Requests:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label: "3 years from project completion or proposal date",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f065: {
    label: "Analytics Data:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f066: {
    label: "26 months (Google Analytics default)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label: "Audit Logs:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f068: {
    label: "7 years for legal and regulatory compliance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f069: {
    label:
      "After the retention period expires, we securely delete or anonymize yo",
    section: "Page copy",
    kind: "text",
    maxLength: 405,
    locked: false,
  },
  f070: {
    label: "6. Where Your Information is Stored",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label:
      "Your personal information is stored on secure servers located in Canad",
    section: "Page copy",
    kind: "text",
    maxLength: 624,
    locked: false,
  },
  f072: {
    label:
      "Some service providers (such as Google Analytics) may process data out",
    section: "Page copy",
    kind: "text",
    maxLength: 747,
    locked: false,
  },
  f073: {
    label: "7. Who We Share Your Information With",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label: "We may share your personal information with:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f075: {
    label: "7.1 Service Providers",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "Cloud Hosting:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f077: {
    label: "Lovable Cloud/Supabase (data storage and processing)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f078: {
    label: "Analytics:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f079: {
    label: "Google Analytics (website usage analysis)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f080: {
    label: "Email Services:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f081: {
    label: "Resend (newsletter delivery)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f082: {
    label: "7.2 Legal Requirements",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f083: {
    label: "We may disclose your information when required by law, such as:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f084: {
    label: "In response to a court order, subpoena, or legal process",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label: "To comply with regulatory requirements (WSIB, CRA, etc.)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f086: {
    label: "To protect our rights, property, or safety",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "To prevent fraud or illegal activity",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label: "7.3 Business Transfers",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label:
      "If we are involved in a merger, acquisition, or sale of assets, your i",
    section: "Page copy",
    kind: "text",
    maxLength: 501,
    locked: false,
  },
  f090: {
    label: "8. Cookies and Tracking Technologies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f091: {
    label: "8.1 What Cookies We Use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f092: {
    label: "Essential Cookies:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f093: {
    label: "Required for website functionality (session management, security)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f094: {
    label: "Analytics Cookies:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f095: {
    label: "Google Analytics to understand how visitors use our site",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f096: {
    label: "Preference Cookies:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f097: {
    label: "Remember your cookie consent choices",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f098: {
    label: "8.2 Why We Use Cookies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f099: {
    label: "Ensure website security and functionality",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f100: {
    label: "Analyze site traffic and usage patterns",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f101: {
    label: "Improve user experience and website performance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f102: {
    label: "Remember your preferences and settings",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f103: {
    label: "8.3 Managing Cookies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f104: {
    label: "You can control cookies through:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f105: {
    label: "Our cookie banner (shown on first visit)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f106: {
    label: "Your browser settings (disable or delete cookies)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f107: {
    label: "Google Analytics opt-out: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f108: {
    label:
      "Note: Disabling essential cookies may affect website functionality.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f109: {
    label: "9. Your Privacy Rights",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f110: {
    label:
      "Under PIPEDA, you have the following rights regarding your personal in",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f111: {
    label: "Right to Access:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f112: {
    label: "Request a copy of the personal information we hold about you",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f113: {
    label: "Right to Correction:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f114: {
    label: "Request correction of inaccurate or incomplete information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f115: {
    label: "Right to Deletion:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f116: {
    label:
      "Request deletion of your personal information (subject to legal retent",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f117: {
    label: "Right to Withdraw Consent:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f118: {
    label: "Unsubscribe from newsletters or withdraw consent at any time",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f119: {
    label: "Right to Object:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f120: {
    label: "Object to certain uses of your information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f121: {
    label: "Right to Complain:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f122: {
    label: "File a complaint with the Privacy Commissioner of Canada",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f123: {
    label: "How to Exercise Your Rights",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f124: {
    label: "To exercise any of these rights, contact us at:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f125: {
    label: "Email:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f126: {
    label: "Phone:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f127: {
    label: "Mail:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f128: {
    label:
      "Ascent Group Construction, Privacy Officer, 2 Jody Ave, North York, ON",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f129: {
    label:
      "We will respond to your request within 30 days as required by PIPEDA.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f130: {
    label: "10. How We Protect Your Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f131: {
    label:
      "We implement appropriate technical and organizational security measure",
    section: "Page copy",
    kind: "text",
    maxLength: 360,
    locked: false,
  },
  f132: {
    label: "Encryption:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f133: {
    label: "SSL/TLS encryption for data transmission",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f134: {
    label: "Access Controls:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f135: {
    label: "Restricted access to personal information on a need-to-know basis",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f136: {
    label: "Secure Storage:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f137: {
    label: "Encrypted database storage with regular backups",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f138: {
    label: "Security Monitoring:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f139: {
    label: "Regular security audits and vulnerability assessments",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f140: {
    label: "Employee Training:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f141: {
    label: "Staff trained on privacy and data protection practices",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f142: {
    label: "Breach Response:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f143: {
    label: "Incident response plan to address potential data breaches",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f144: {
    label:
      "While we strive to protect your information, no method of transmission",
    section: "Page copy",
    kind: "text",
    maxLength: 429,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f145: {
    label: "11. Children's Privacy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f146: {
    label:
      "Our website and services are not directed to individuals under the age",
    section: "Page copy",
    kind: "text",
    maxLength: 801,
    locked: false,
  },
  f147: {
    label: "12. Changes to This Privacy Policy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f148: {
    label:
      "We may update this Privacy Policy periodically to reflect changes in o",
    section: "Page copy",
    kind: "text",
    maxLength: 678,
    locked: false,
  },
  f149: {
    label:
      "Material changes will be communicated through a prominent notice on ou",
    section: "Page copy",
    kind: "text",
    maxLength: 639,
    locked: false,
  },
  f150: {
    label: "13. Contact Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f151: {
    label: "Privacy Officer",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f152: {
    label:
      "For questions, concerns, or requests regarding this Privacy Policy or ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f153: {
    label: "Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f154: {
    label: "Privacy Officer",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f155: {
    label: "Email: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f156: {
    label: "Phone: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f157: {
    label:
      "If you are not satisfied with our response, you may file a complaint w",
    section: "Page copy",
    kind: "text",
    maxLength: 372,
    locked: false,
  },
  f158: {
    label: "www.priv.gc.ca",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f159: {
    label: "14. PIPEDA Compliance Statement",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f160: {
    label:
      "This Privacy Policy has been designed to comply with Canada's Personal",
    section: "Page copy",
    kind: "text",
    maxLength: 891,
    locked: false,
  },
} as const;
const module = defineContent("privacy", defaults, meta);
export const schema = module.schema;
export default module;
