import { defineContent } from "../types";
export const defaults = {
  f001: "Our Projects | Ascent Group Construction",
  f002: "Browse our growing portfolio of construction and restoration projects across the GTA. Commercial, residential, and institutional envelope and interior work.",
  f003: "Featured Projects",
  f004: "Showcasing our most notable work",
  f005: "↻ Refresh selection",
  f006: "Loading projects...",
  f007: "No projects found matching your criteria",
  f008: "Clear Filters",
  f009: "All Projects",
  f010: "project",
  f011: "found",
  f012: "Show More Projects",
  f013: "Showing ",
  f014: "of ",
  f015: "People Also Ask",
  f016: "Common questions about our project portfolio.",
  f017: "All Projects",
  f019: "Commercial",
  f021: "Residential",
  f023: "Institutional",
  f025: "Industrial",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 468,
    locked: false,
  },
  f003: {
    label: "Featured Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "Showcasing our most notable work",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "↻ Refresh selection",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "Loading projects...",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "No projects found matching your criteria",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "Clear Filters",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "All Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "project",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "found",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "Show More Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "Showing ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "of ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("projects", defaults, meta);
export const schema = module.schema;
export default module;
