import { defineContent } from "../types";
export const defaults = {
  f001: "Capital Planning Support",
  f002: "Reserve fund study-aligned envelope repairs with clear documentation and manufacturer warranties",
  f003: "Occupied Building Expertise",
  f004: "Phased execution, tenant coordination, and off-hours work to minimize disruption",
  f005: "Multi-Property Programs",
  f006: "Consistent service across your portfolio with dedicated project managers and volume pricing",
  f007: "Full Compliance",
  f008: "$2M CGL coverage, active WSIB registration, and comprehensive site safety protocols",
  f009: "48-72 Hour Response",
  f010: "Emergency site visits for active water intrusion and urgent facade issues",
  f011: "Façade Remediation",
  f012: "Cladding repairs, sealant replacement, EIFS/stucco restoration for mid-rise buildings",
  f013: "Parking Garage Rehabilitation",
  f014: "Concrete restoration, waterproofing, protective coatings, traffic membrane systems",
  f015: "Suite Turnovers",
  f016: "3-day turnarounds for 1-2 bedroom units: painting, patching, flooring coordination",
  f017: "Common Area Refresh",
  f018: "Lobbies, hallways, amenity spaces—commercial-grade finishes on property management timelines",
  f019: "Sealant Maintenance Programs",
  f020: "10-12 year replacement cycles for window perimeters, expansion joints, curtain wall systems",
  f021: "Balcony Waterproofing",
  f022: "Membrane replacement, tile over concrete, drainage solutions for occupied buildings",
  f023: "Site Assessment",
  f024: "Scheduling",
  f025: "Execution",
  f026: "Completion",
  f027: "Property Management Services - Envelope & Restoration for Multi-Residential",
  f028: "Façade remediation, parking garage restoration, and unit turnovers for 10-30 story condominiums in Toronto and GTA. Reserve fund study-aligned. WSIB compliant. Fast response for active leaks.",
  f029: "For Property Managers",
  f030: "Envelope & Restoration Partner for Multi-Residential Properties",
  f031: "Façade remediation, parking garage repairs, and unit turnovers for 10-30 story condominiums across the GTA. Fast response, clear documentation, reserve fund study-aligned work.",
  f032: "Property management construction services",
  f033: "Contact Us",
  f034: "Home",
  f035: "Property Managers",
  f036: "Reserve Fund Aligned",
  f037: "Fast Response",
  f038: "Clear Documentation",
  f039: "Built for Property Management Success",
  f040: "We help you maximize value, minimize downtime, and keep tenants happy",
  f041: "Services That Deliver ROI",
  f042: "Every service designed to increase property value and tenant satisfaction",
  f043: "Streamlined Process",
  f044: "Why Property Managers Trust Us",
  f045: "Operational capabilities built around occupied-building requirements",
  f046: "Common Questions from Property Managers",
  f047: "Procurement, scheduling, documentation, and reserve fund alignment — answered.",
  f048: "Let's Discuss Your Property Needs",
  f049: "Volume pricing available for multi-unit properties and ongoing maintenance contracts",
  f050: "Contact Us",
  f051: "Request a Proposal",
  f052: "Related Resources for Property Managers",
  f053: "Emergency Building Repair",
  f054: "Same-day site assessment for active leaks, facade failure, or storm damage on your buildings.",
  f055: "Restoration & Capital Programs",
  f056: "Parking-garage restoration, balcony waterproofing, and sealant cycles aligned with your reserve fund study.",
  f057: "Capabilities & Documentation",
  f058: "Self-perform crew details, insurance, WSIB, and the full Ascent operational capability statement.",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f009: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f010: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 573,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f029: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 528,
    locked: false,
  },
  f032: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f047: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f054: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f055: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 321,
    locked: false,
  },
  f057: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
} as const;
const module = defineContent("property-managers", defaults, meta);
export const schema = module.schema;
export default module;
