import { defineContent } from "../types";
export const defaults = {
  f001: "Toronto & GTA Core",
  f002: "Richmond Hill",
  f003: "Durham Region",
  f004: "York Region",
  f005: "King City",
  f006: "Halton & Hamilton",
  f007: "Service Areas | Ascent Group Construction",
  f008: "Serving Toronto, Mississauga, Brampton, Vaughan, Markham and the Greater Toronto Area with professional building envelope, restoration, and specialty trade services.",
  f009: "Service Coverage",
  f010: "Service Areas",
  f011: "Professional building envelope and interior trade services across the Greater Toronto Area",
  f012: "Service coverage areas across Ontario",
  f013: "Get a Quote",
  f014: "Home",
  f015: "Resources",
  f016: "Service Areas",
  f017: "Our Service Coverage",
  f018: "Primary Service Area",
  f019: "100km radius from Toronto - Same-day service available",
  f020: "Extended Coverage",
  f021: "Up to 200km - Available for larger projects",
  f022: "Primary Service Cities",
  f023: "Areas with same-day emergency service and fastest response times",
  f024: "Coverage by Region",
  f025: "Complete Coverage Area",
  f026: "All cities and municipalities we serve",
  f027: "Service Availability",
  f028: "Emergency Services",
  f029: "Available for urgent repairs within GTA core for active leaks and envelope failures",
  f030: "Regular Projects",
  f031: "All of Southern Ontario covered for scheduled building envelope and restoration projects",
  f032: "Large Projects",
  f033: "Province-wide consideration for major commercial and multi-unit developments",
  f034: "Not Sure If We Serve Your Area?",
  f035: "Contact us to confirm coverage. We're always expanding our service area and may accommodate special projects outside our typical range.",
  f036: "Start Your Project",
  f037: "Service Area FAQ",
  f038: "Common questions about coverage, mobilization, and travel.",
  f039: "Plan Your Project",
  f040: "Resources to scope and schedule across the GTA and beyond.",
  f041: "Capabilities",
  f042: "What we self-perform and how we deliver.",
  f043: "Emergency Repairs",
  f044: "Same-day response for active envelope failures.",
  f045: "Contractor Portal",
  f046: "Vendor packet, unit rates, and RFQs.",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 495,
    locked: false,
  },
  f009: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Our Service Coverage",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "Primary Service Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "100km radius from Toronto - Same-day service available",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Extended Coverage",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "Up to 200km - Available for larger projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "Primary Service Cities",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "Areas with same-day emergency service and fastest response times",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Coverage by Region",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Complete Coverage Area",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "All cities and municipalities we serve",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Service Availability",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Emergency Services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label:
      "Available for urgent repairs within GTA core for active leaks and enve",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "Regular Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label:
      "All of Southern Ontario covered for scheduled building envelope and re",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "Large Projects",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label:
      "Province-wide consideration for major commercial and multi-unit develo",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "Not Sure If We Serve Your Area?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label:
      "Contact us to confirm coverage. We're always expanding our service are",
    section: "Page copy",
    kind: "text",
    maxLength: 405,
    locked: false,
  },
  f036: {
    label: "Start Your Project",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "Service Area FAQ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Common questions about coverage, mobilization, and travel.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("resources-service-areas", defaults, meta);
export const schema = module.schema;
export default module;
