import { defineContent } from "../types";
export const defaults = {
  f001: "Home",
  f002: "Services",
  f003: "Specialty Contracting Services",
  f004: "Self-performed and coordinated specialty contracting — envelope, restoration, cladding, masonry, painting, and interior trades across Ontario.",
  f005: "Services",
  f006: "Specialty contracting services for envelope, restoration, and interior trade execution",
  f007: "Self-performed and coordinated scopes across commercial, multi-unit, and residential projects in Ontario.",
  f008: "Specialty contracting services — building envelope and interior trades",
  f009: "Start a Project",
  f010: "Request Site Assessment",
  f011: "Home",
  f012: "Services",
  f013: "Self-Performed Work",
  f014: "Licensed & Insured",
  f015: "GTA Coverage",
  f016: "Three Categories. One Self-Perform Crew.",
  f017: "Every service we offer lives in one of three categories. Each is delivered by the same accountable crew — no broker, no markup layers.",
  f018: "Manufacturer Systems We Install",
  f019: "We install to manufacturer specifications using approved systems from leading envelope, coating, and restoration product lines.",
  f020: "People Also Ask",
  f021: "Common questions about our services, certifications, and how we deliver.",
  f022: "EIFS & stucco, balcony waterproofing, and architectural cladding — the systems that keep buildings dry, efficient, and intact.",
  f023: "Sto Canada Listed Installer (SCL-001 → SCL-010)",
  f024: "Dryvit, Parex, and Sto cladding systems",
  f025: "Exterior waterproofing and envelope systems",
  f026: "Masonry restoration, sealant renewal, concrete repair, and parking garage rehabilitation — full lifecycle scopes for property managers and capital planners.",
  f027: "Concrete spall repair & rebar treatment",
  f028: "Parking garage coatings & line marking",
  f029: "Masonry repair & sealant replacement programs",
  f030: "Painting, tile, drywall, and flooring — interior buildouts and finishing work executed by the same self-perform crews running our envelope scopes.",
  f031: "Commercial & residential painting",
  f032: "Tile, resilient flooring, and finishes",
  f033: "Drywall, framing, and tenant buildouts",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 426,
    locked: false,
  },
  f005: {
    label: "eyebrow",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 315,
    locked: false,
  },
  f008: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f015: {
    label: "text",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 402,
    locked: false,
  },
  f018: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 381,
    locked: false,
  },
  f020: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 378,
    locked: false,
  },
  f023: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f024: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f025: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 468,
    locked: false,
  },
  f027: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 438,
    locked: false,
  },
  f031: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "List item",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("services", defaults, meta);
export const schema = module.schema;
export default module;
