import { defineContent } from "../types";
export const defaults = {
  f001: "Company Info",
  f002: "Project Details",
  f003: "Timeline",
  f004: "Scope of Work",
  f005: "Submit RFP - Request for Proposal | Ascent Group Construction",
  f006: "Submit your building envelope or restoration RFP to Ascent Group Construction. Multi-step form for commercial, multi-family, and institutional projects across Ontario.",
  f007: "Submit Your RFP",
  f008: "Complete our 4-step form to receive a detailed construction proposal",
  f009: "Submit your construction RFP",
  f010: "Home",
  f011: "Submit RFP",
  f012: "RFP Received",
  f013: "Thank you for your proposal. Our estimating team will review and respond within 2 business days.",
  f014: "Reference ID",
  f015: "Submitted ",
  f016: "Copied",
  f017: "Copy ID",
  f018: "Please reference this ID in any follow-up correspondence with our team.",
  f019: "What happens next",
  f020: "Review (24–48 hours)",
  f021: "Our estimating team reviews your project requirements.",
  f022: "Initial contact (within 2 business days)",
  f023: "We reach out to discuss details and clarify questions.",
  f024: "Proposal & presentation",
  f025: "We prepare and walk you through a tailored proposal.",
  f026: "file",
  f027: "selected for upload.",
  f028: "A confirmation has been sent to your email address.",
  f029: "Return Home",
  f030: "Contact Us",
  f031: "View in Admin Inbox",
  f032: "Step ",
  f033: "of ",
  f034: "% Complete",
  f035: "Company website (leave blank)",
  f037: "Back",
  f038: "Next",
  f039: "Submit RFP",
  f040: "Need Help?",
  f041: "Have questions about the RFP process or need assistance with your submission?",
  f042: "📞 Call Us",
  f043: "📧 Email",
};
export const meta = {
  f001: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f005: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 501,
    locked: false,
  },
  f007: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "RFP Received",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label:
      "Thank you for your proposal. Our estimating team will review and respo",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "Reference ID",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "Submitted ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Copied",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Copy ID",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label:
      "Please reference this ID in any follow-up correspondence with our team",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "What happens next",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Review (24–48 hours)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f021: {
    label: "Our estimating team reviews your project requirements.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "Initial contact (within 2 business days)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "We reach out to discuss details and clarify questions.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Proposal & presentation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "We prepare and walk you through a tailored proposal.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "file",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "selected for upload.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "A confirmation has been sent to your email address.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Return Home",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "Contact Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f031: {
    label: "View in Admin Inbox",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f032: {
    label: "Step ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "of ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "% Complete",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "Company website (leave blank)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f037: {
    label: "Back",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label: "Next",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f039: {
    label: "Submit RFP",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "Need Help?",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label:
      "Have questions about the RFP process or need assistance with your subm",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "📞 Call Us",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "📧 Email",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("submit-rfp", defaults, meta);
export const schema = module.schema;
export default module;
