import { defineContent } from "../types";
export const defaults = {
  f001: "Terms of Use | Ascent Group Construction",
  f003: "Terms of Use for Ascent Group Construction website - legal terms, disclaimers, and conditions for using our services.",
  f005: "index, follow",
  f006: "Terms of Use",
  f007: "Last Updated: ",
  f008: "1. Acceptance of Terms",
  f009: 'Welcome to the Ascent Group Construction website (the "Website"). By accessing or using this Website, you agree to be bound by these Terms of Use and our ',
  f010: "Privacy Policy",
  f011: ". If you do not agree to these terms, please do not use this Website.",
  f012: 'These Terms of Use constitute a legally binding agreement between you and Ascent Group Construction ("Company," "we," "our," or "us").',
  f013: "2. Use of Website",
  f014: "2.1 Permitted Use",
  f015: "You may use this Website for:",
  f016: "Viewing information about our construction services",
  f017: "Submitting inquiries, RFP requests, and job applications",
  f018: "Subscribing to our newsletter (with consent)",
  f019: "Viewing our project portfolio and case studies",
  f020: "Accessing publicly available resources and content",
  f021: "2.2 Prohibited Use",
  f022: "You may NOT:",
  f023: "Use the Website for any unlawful purpose or in violation of these Terms",
  f024: "Attempt to gain unauthorized access to our systems or networks",
  f025: "Transmit viruses, malware, or other harmful code",
  f026: "Scrape, copy, or reproduce content without permission",
  f027: "Impersonate any person or entity",
  f028: "Interfere with the proper functioning of the Website",
  f029: "Use automated systems (bots, scrapers) without authorization",
  f030: "3. No Warranty of Accuracy",
  f031: "The information provided on this Website is for general informational purposes only. While we strive to keep the information accurate and up-to-date, we make no representations or warranties of any kind, express or implied, about:",
  f032: "The accuracy, completeness, or reliability of any information",
  f033: "The availability or functionality of the Website",
  f034: "The suitability of our services for your specific needs",
  f035: "The results you may achieve from using our services",
  f036: "Information on this Website may contain technical inaccuracies or typographical errors. We reserve the right to make changes, corrections, and updates at any time without notice.",
  f037: "4. Not Professional Advice",
  f038: "The content on this Website is for informational purposes only and does not constitute professional construction, engineering, architectural, legal, or financial advice. You should not rely solely on information from this Website for important decisions.",
  f039: "For specific construction projects, you should:",
  f040: "Obtain a detailed project proposal and contract",
  f041: "Consult with qualified professionals (engineers, architects, lawyers)",
  f042: "Obtain necessary permits and approvals",
  f043: "Review project specifications and drawings",
  f044: "Conduct proper due diligence",
  f045: "5. Limitation of Liability",
  f046: "To the fullest extent permitted by applicable law, Ascent Group Construction and its directors, officers, employees, agents, and affiliates shall not be liable for:",
  f047: "Any direct, indirect, incidental, special, consequential, or punitive damages",
  f048: "Loss of profits, revenue, data, or business opportunities",
  f049: "Website downtime, errors, or technical failures",
  f050: "Reliance on information provided on the Website",
  f051: "Unauthorized access to or alteration of your transmissions or data",
  f052: "Third-party content, links, or services",
  f053: "This limitation applies regardless of whether we were advised of the possibility of such damages and regardless of the theory of liability (contract, tort, negligence, strict liability, or otherwise).",
  f054: "Some jurisdictions do not allow the exclusion or limitation of certain damages. In such jurisdictions, our liability is limited to the greatest extent permitted by law.",
  f055: "6. Third-Party Links and Content",
  f056: "This Website may contain links to third-party websites, partner sites, or external resources. These links are provided for your convenience only. We do not:",
  f057: "Control or endorse the content of third-party websites",
  f058: "Make any representations about third-party services or products",
  f059: "Assume responsibility for the accuracy or legality of third-party content",
  f060: "Guarantee the privacy practices of third-party sites",
  f061: "Your use of third-party websites is at your own risk and subject to their terms and conditions. We recommend reviewing the terms and privacy policies of any external sites you visit.",
  f062: "7. Intellectual Property Rights",
  f063: "7.1 Our Content",
  f064: "All content on this Website, including text, graphics, logos, images, videos, software, and compilation, is the property of Ascent Group Construction or its licensors and is protected by Canadian and international copyright laws.",
  f065: "You may not reproduce, distribute, modify, create derivative works, publicly display, or exploit any content without our prior written permission.",
  f066: "7.2 Trademarks",
  f067: '"Ascent Group Construction" and our logo are trademarks of Ascent Group Construction. You may not use our trademarks without our express written consent.',
  f068: "7.3 Partner Logos and Trademarks",
  f069: "Third-party logos, trademarks, and brand names displayed on this Website are the property of their respective owners. Their display on our Website:",
  f070: "Is done with permission or under applicable trademark fair use provisions",
  f071: "Does not imply endorsement of our services by those parties",
  f072: "Does not grant you any right to use those marks",
  f073: "7.4 Project Photos and Images",
  f074: "Project photographs and images are used with permission from clients or are our original work. Unauthorized use of project images may violate copyright and privacy rights.",
  f075: "8. Credentials and Certifications",
  f076: "8.1 WSIB Compliance",
  f077: "Ascent Group Construction maintains WSIB (Workplace Safety and Insurance Board) clearance as required for construction contractors in Ontario. Our current WSIB clearance certificate is available upon request.",
  f078: "WSIB clearance status can be verified through the WSIB's online clearance verification tool at ",
  f079: "www.wsib.ca",
  f080: "8.2 Licensing and Insurance",
  f081: "We are a fully licensed and insured construction contractor. Proof of licensing, bonding, and insurance coverage is available upon request for qualified project inquiries.",
  f082: "8.3 Certifications",
  f083: "Certifications, awards, and memberships displayed on this Website are current as of the date shown. We maintain documentation to substantiate all claims regarding our credentials.",
  f084: "9. Testimonials and Reviews",
  f085: "We are currently collecting verified client testimonials for display on this Website. When testimonials are displayed, they will:",
  f086: "Represent genuine experiences of actual clients",
  f087: "Be obtained with proper written consent and documentation",
  f088: "Reflect the client's authentic experience at the time of the project",
  f089: "Not be fabricated, purchased, or materially altered",
  f090: "Include disclosure of any material connection, compensation, or incentive provided",
  f091: "Comply with FTC Guidelines and Canadian advertising standards",
  f092: "We maintain documentation to verify the authenticity of all testimonials, including:",
  f093: "Client consent forms with signatures and dates",
  f094: "Project documentation proving the business relationship",
  f095: "Contact information for verification purposes (kept confidential)",
  f096: "Important Notice:",
  f097: "Individual results may vary. Past performance is not necessarily indicative of future results. Your experience may differ based on project scope, timeline, budget, site conditions, and other factors specific to your project.",
  f098: "10. User-Submitted Content",
  f099: 'When you submit content through our contact forms, RFP submissions, or other communications (collectively, "User Content"), you:',
  f100: "Grant us a license to use, store, and process your submission for business purposes",
  f101: "Represent that you have the right to submit the content",
  f102: "Acknowledge that submissions are not confidential (except as covered by our Privacy Policy)",
  f103: "Agree not to submit confidential, proprietary, or sensitive information without a proper confidentiality agreement",
  f104: "11. Indemnification",
  f105: "You agree to indemnify, defend, and hold harmless Ascent Group Construction, its officers, directors, employees, agents, and affiliates from any claims, liabilities, damages, losses, costs, or expenses (including reasonable legal fees) arising from:",
  f106: "Your use or misuse of the Website",
  f107: "Your violation of these Terms of Use",
  f108: "Your violation of any third-party rights",
  f109: "Any content you submit through the Website",
  f110: "12. Changes to Terms",
  f111: 'We reserve the right to modify these Terms of Use at any time. Changes will be effective immediately upon posting to this page with an updated "Last Updated" date. Material changes may be communicated through a prominent notice on the Website.',
  f112: "Your continued use of the Website after changes are posted constitutes acceptance of the modified Terms. We encourage you to review these Terms periodically.",
  f113: "13. Governing Law and Jurisdiction",
  f114: "These Terms of Use are governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict of law principles.",
  f115: "Any disputes arising from these Terms or your use of the Website shall be subject to the exclusive jurisdiction of the courts located in Ontario, Canada.",
  f116: "14. Severability",
  f117: "If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.",
  f118: "15. Entire Agreement",
  f119: "These Terms of Use, together with our Privacy Policy and any other legal notices published on this Website, constitute the entire agreement between you and Ascent Group Construction regarding your use of the Website.",
  f120: "16. Contact Information",
  f121: "For questions or concerns about these Terms of Use:",
  f122: "Ascent Group Construction",
  f123: "Legal Department",
  f124: "Email: ",
  f125: "Phone: ",
  f126: "Acknowledgment",
  f127: "By using this Website, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use and our Privacy Policy.",
};
export const meta = {
  f001: {
    label: "Terms of Use | Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 351,
    locked: false,
  },
  f005: {
    label: "content",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "Terms of Use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "Last Updated: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "1. Acceptance of Terms",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label:
      'Welcome to the Ascent Group Construction website (the "Website"). By a',
    section: "Page copy",
    kind: "text",
    maxLength: 462,
    locked: false,
  },
  f010: {
    label: "Privacy Policy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label:
      ". If you do not agree to these terms, please do not use this Website.",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label:
      "These Terms of Use constitute a legally binding agreement between you ",
    section: "Page copy",
    kind: "text",
    maxLength: 402,
    locked: false,
  },
  f013: {
    label: "2. Use of Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label: "2.1 Permitted Use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "You may use this Website for:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Viewing information about our construction services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Submitting inquiries, RFP requests, and job applications",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "Subscribing to our newsletter (with consent)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "Viewing our project portfolio and case studies",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "Accessing publicly available resources and content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "2.2 Prohibited Use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "You may NOT:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label:
      "Use the Website for any unlawful purpose or in violation of these Term",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "Attempt to gain unauthorized access to our systems or networks",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "Transmit viruses, malware, or other harmful code",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "Scrape, copy, or reproduce content without permission",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f027: {
    label: "Impersonate any person or entity",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f028: {
    label: "Interfere with the proper functioning of the Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f029: {
    label: "Use automated systems (bots, scrapers) without authorization",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f030: {
    label: "3. No Warranty of Accuracy",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f031: {
    label:
      "The information provided on this Website is for general informational ",
    section: "Page copy",
    kind: "text",
    maxLength: 690,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f032: {
    label: "The accuracy, completeness, or reliability of any information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f033: {
    label: "The availability or functionality of the Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f034: {
    label: "The suitability of our services for your specific needs",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f035: {
    label: "The results you may achieve from using our services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f036: {
    label:
      "Information on this Website may contain technical inaccuracies or typo",
    section: "Page copy",
    kind: "text",
    maxLength: 534,
    locked: false,
  },
  f037: {
    label: "4. Not Professional Advice",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f038: {
    label:
      "The content on this Website is for informational purposes only and doe",
    section: "Page copy",
    kind: "text",
    maxLength: 762,
    locked: false,
  },
  f039: {
    label: "For specific construction projects, you should:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f040: {
    label: "Obtain a detailed project proposal and contract",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f041: {
    label:
      "Consult with qualified professionals (engineers, architects, lawyers)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f042: {
    label: "Obtain necessary permits and approvals",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f043: {
    label: "Review project specifications and drawings",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f044: {
    label: "Conduct proper due diligence",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f045: {
    label: "5. Limitation of Liability",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f046: {
    label:
      "To the fullest extent permitted by applicable law, Ascent Group Constr",
    section: "Page copy",
    kind: "text",
    maxLength: 492,
    locked: false,
  },
  f047: {
    label:
      "Any direct, indirect, incidental, special, consequential, or punitive ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f048: {
    label: "Loss of profits, revenue, data, or business opportunities",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f049: {
    label: "Website downtime, errors, or technical failures",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f050: {
    label: "Reliance on information provided on the Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f051: {
    label: "Unauthorized access to or alteration of your transmissions or data",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f052: {
    label: "Third-party content, links, or services",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f053: {
    label:
      "This limitation applies regardless of whether we were advised of the p",
    section: "Page copy",
    kind: "text",
    maxLength: 600,
    locked: false,
  },
  f054: {
    label:
      "Some jurisdictions do not allow the exclusion or limitation of certain",
    section: "Page copy",
    kind: "text",
    maxLength: 504,
    locked: false,
  },
  f055: {
    label: "6. Third-Party Links and Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f056: {
    label:
      "This Website may contain links to third-party websites, partner sites,",
    section: "Page copy",
    kind: "text",
    maxLength: 468,
    locked: false,
  },
  f057: {
    label: "Control or endorse the content of third-party websites",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f058: {
    label: "Make any representations about third-party services or products",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f059: {
    label:
      "Assume responsibility for the accuracy or legality of third-party cont",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f060: {
    label: "Guarantee the privacy practices of third-party sites",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f061: {
    label:
      "Your use of third-party websites is at your own risk and subject to th",
    section: "Page copy",
    kind: "text",
    maxLength: 546,
    locked: false,
  },
  f062: {
    label: "7. Intellectual Property Rights",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f063: {
    label: "7.1 Our Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f064: {
    label:
      "All content on this Website, including text, graphics, logos, images, ",
    section: "Page copy",
    kind: "text",
    maxLength: 687,
    locked: false,
  },
  f065: {
    label:
      "You may not reproduce, distribute, modify, create derivative works, pu",
    section: "Page copy",
    kind: "text",
    maxLength: 438,
    locked: false,
  },
  f066: {
    label: "7.2 Trademarks",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f067: {
    label:
      '"Ascent Group Construction" and our logo are trademarks of Ascent Grou',
    section: "Page copy",
    kind: "text",
    maxLength: 459,
    locked: false,
  },
  f068: {
    label: "7.3 Partner Logos and Trademarks",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f069: {
    label:
      "Third-party logos, trademarks, and brand names displayed on this Websi",
    section: "Page copy",
    kind: "text",
    maxLength: 441,
    locked: false,
  },
  f070: {
    label:
      "Is done with permission or under applicable trademark fair use provisi",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f071: {
    label: "Does not imply endorsement of our services by those parties",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f072: {
    label: "Does not grant you any right to use those marks",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f073: {
    label: "7.4 Project Photos and Images",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f074: {
    label:
      "Project photographs and images are used with permission from clients o",
    section: "Page copy",
    kind: "text",
    maxLength: 513,
    locked: false,
  },
  f075: {
    label: "8. Credentials and Certifications",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f076: {
    label: "8.1 WSIB Compliance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f077: {
    label:
      "Ascent Group Construction maintains WSIB (Workplace Safety and Insuran",
    section: "Page copy",
    kind: "text",
    maxLength: 624,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f078: {
    label:
      "WSIB clearance status can be verified through the WSIB's online cleara",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f079: {
    label: "www.wsib.ca",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f080: {
    label: "8.2 Licensing and Insurance",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f081: {
    label:
      "We are a fully licensed and insured construction contractor. Proof of ",
    section: "Page copy",
    kind: "text",
    maxLength: 513,
    locked: true,
    help: "Protected company claim: owner review required.",
  },
  f082: {
    label: "8.3 Certifications",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f083: {
    label:
      "Certifications, awards, and memberships displayed on this Website are ",
    section: "Page copy",
    kind: "text",
    maxLength: 537,
    locked: false,
  },
  f084: {
    label: "9. Testimonials and Reviews",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f085: {
    label:
      "We are currently collecting verified client testimonials for display o",
    section: "Page copy",
    kind: "text",
    maxLength: 387,
    locked: false,
  },
  f086: {
    label: "Represent genuine experiences of actual clients",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f087: {
    label: "Be obtained with proper written consent and documentation",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f088: {
    label:
      "Reflect the client's authentic experience at the time of the project",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f089: {
    label: "Not be fabricated, purchased, or materially altered",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f090: {
    label:
      "Include disclosure of any material connection, compensation, or incent",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f091: {
    label: "Comply with FTC Guidelines and Canadian advertising standards",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f092: {
    label:
      "We maintain documentation to verify the authenticity of all testimonia",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f093: {
    label: "Client consent forms with signatures and dates",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f094: {
    label: "Project documentation proving the business relationship",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f095: {
    label: "Contact information for verification purposes (kept confidential)",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f096: {
    label: "Important Notice:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f097: {
    label:
      "Individual results may vary. Past performance is not necessarily indic",
    section: "Page copy",
    kind: "text",
    maxLength: 672,
    locked: false,
  },
  f098: {
    label: "10. User-Submitted Content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f099: {
    label:
      "When you submit content through our contact forms, RFP submissions, or",
    section: "Page copy",
    kind: "text",
    maxLength: 384,
    locked: false,
  },
  f100: {
    label:
      "Grant us a license to use, store, and process your submission for busi",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f101: {
    label: "Represent that you have the right to submit the content",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f102: {
    label:
      "Acknowledge that submissions are not confidential (except as covered b",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f103: {
    label:
      "Agree not to submit confidential, proprietary, or sensitive informatio",
    section: "Page copy",
    kind: "text",
    maxLength: 342,
    locked: false,
  },
  f104: {
    label: "11. Indemnification",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f105: {
    label:
      "You agree to indemnify, defend, and hold harmless Ascent Group Constru",
    section: "Page copy",
    kind: "text",
    maxLength: 747,
    locked: false,
  },
  f106: {
    label: "Your use or misuse of the Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f107: {
    label: "Your violation of these Terms of Use",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f108: {
    label: "Your violation of any third-party rights",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f109: {
    label: "Any content you submit through the Website",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f110: {
    label: "12. Changes to Terms",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f111: {
    label:
      "We reserve the right to modify these Terms of Use at any time. Changes",
    section: "Page copy",
    kind: "text",
    maxLength: 729,
    locked: false,
  },
  f112: {
    label:
      "Your continued use of the Website after changes are posted constitutes",
    section: "Page copy",
    kind: "text",
    maxLength: 471,
    locked: false,
  },
  f113: {
    label: "13. Governing Law and Jurisdiction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f114: {
    label:
      "These Terms of Use are governed by and construed in accordance with th",
    section: "Page copy",
    kind: "text",
    maxLength: 600,
    locked: false,
  },
  f115: {
    label:
      "Any disputes arising from these Terms or your use of the Website shall",
    section: "Page copy",
    kind: "text",
    maxLength: 459,
    locked: false,
  },
  f116: {
    label: "14. Severability",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f117: {
    label:
      "If any provision of these Terms is found to be invalid, illegal, or un",
    section: "Page copy",
    kind: "text",
    maxLength: 873,
    locked: false,
  },
  f118: {
    label: "15. Entire Agreement",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f119: {
    label:
      "These Terms of Use, together with our Privacy Policy and any other leg",
    section: "Page copy",
    kind: "text",
    maxLength: 648,
    locked: false,
  },
  f120: {
    label: "16. Contact Information",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f121: {
    label: "For questions or concerns about these Terms of Use:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f122: {
    label: "Ascent Group Construction",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f123: {
    label: "Legal Department",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f124: {
    label: "Email: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f125: {
    label: "Phone: ",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f126: {
    label: "Acknowledgment",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f127: {
    label:
      "By using this Website, you acknowledge that you have read, understood,",
    section: "Page copy",
    kind: "text",
    maxLength: 414,
    locked: false,
  },
} as const;
const module = defineContent("terms", defaults, meta);
export const schema = module.schema;
export default module;
