import { defineContent } from "../types";
export const defaults = {
  f001: "Home",
  f002: "Why Specialty Contractor",
  f003: "Specialty Contractor vs General Contractor | Building Envelope & Restoration",
  f004: "Understand why building envelope & restoration projects benefit from specialty contractors. Compare delivery models, cost structures, and project approaches for Ontario & GTA projects.",
  f005: "Specialty contractor building envelope work",
  f006: "Home",
  f007: "Why Specialty Contractor",
  f008: "Factor",
  f009: "Specialty Contractor",
  f010: "General Contractor",
  f011: "Specialty Contractor",
  f012: "General Contractor",
  f013: "Understanding Different Project Approaches",
  f014: "When to use specialty contractors, general contractors, or hybrid approaches",
  f015: "How project budgets flow through different delivery models",
  f016: "Benefits of this model:",
  f017: "Benefits of this model:",
  f018: "Frequently Asked Questions",
  f019: "What Our Clients Say",
  f020: "Continue Exploring",
  f021: "Capabilities & Self-Perform",
  f022: "How our self-performed model removes sub-tier markups and shortens accountability chains.",
  f023: "Building Envelope Services",
  f024: "EIFS, masonry, sealants, cladding, waterproofing — the specialty scopes we execute directly.",
  f025: "For General Contractors",
  f026: "How GCs partner with Ascent as a reliable specialty trade subcontractor on commercial projects.",
};
export const meta = {
  f001: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f002: {
    label: "name",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f003: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f004: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 552,
    locked: false,
  },
  f005: {
    label: "imageAlt",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f006: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f007: {
    label: "label",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f008: {
    label: "Factor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f009: {
    label: "Specialty Contractor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f010: {
    label: "General Contractor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f011: {
    label: "Specialty Contractor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f012: {
    label: "General Contractor",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f013: {
    label: "Understanding Different Project Approaches",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f014: {
    label:
      "When to use specialty contractors, general contractors, or hybrid appr",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f015: {
    label: "How project budgets flow through different delivery models",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f016: {
    label: "Benefits of this model:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f017: {
    label: "Benefits of this model:",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f018: {
    label: "Frequently Asked Questions",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f019: {
    label: "What Our Clients Say",
    section: "Page copy",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f020: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f021: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f022: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f023: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f024: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f025: {
    label: "title",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
  f026: {
    label: "description",
    section: "Sections and structured data",
    kind: "text",
    maxLength: 300,
    locked: false,
  },
} as const;
const module = defineContent("why-specialty-contractor", defaults, meta);
export const schema = module.schema;
export default module;
