// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.2.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.116.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List Ascent Group construction projects with their status, location, category and publish state.",
  inputSchema: {
    search: z.string().nullable().describe("Optional text to match against the project title or location."),
    featured_only: z.boolean().nullable().describe("When true, return only projects flagged as featured."),
    limit: z.number().int().nullable().describe("Maximum number of projects to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, featured_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("projects").select(
      "id, title, slug, category, location, client_type, project_status, publish_state, featured, completion_date, description"
    ).order("completion_date", { ascending: false, nullsFirst: false }).limit(take);
    if (featured_only) query = query.eq("featured", true);
    // Strip PostgREST filter metacharacters so caller text cannot alter the filter.
    const safeSearch = (search ?? "").replace(/[^\p{L}\p{N}\s\-']/gu, " ").trim().slice(0, 100);
    if (safeSearch) query = query.or(`title.ilike.%${safeSearch}%,location.ilike.%${safeSearch}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z2 } from "npm:zod@^4.6.5";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Get the full detail of one Ascent Group project by its slug, including scope, results and SEO fields.",
  inputSchema: {
    slug: z2.string().describe("The project slug, for example 'queen-street-facade-restoration'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("projects").select(
      "id, title, slug, category, description, location, client_name, client_type, project_status, project_value, project_size, duration, completion_date, delivery_method, scope_of_work, challenge, results, featured, publish_state, seo_title, seo_description"
    ).eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No project found with slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z3 } from "npm:zod@^4.6.5";
var list_services_default = defineTool3({
  name: "list_services",
  title: "List services",
  description: "List the services Ascent Group offers, with category, tier, short description and publish state.",
  inputSchema: {
    category: z3.string().nullable().describe("Optional category to filter on."),
    featured_only: z3.boolean().nullable().describe("When true, return only featured services."),
    limit: z3.number().int().nullable().describe("Maximum number of services to return (default 50, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, featured_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 50, 1), 100);
    let query = supabaseForUser(ctx).from("services").select(
      "id, name, slug, category, service_tier, short_description, typical_timeline, featured, publish_state"
    ).order("name").limit(take);
    if (category) query = query.eq("category", category);
    if (featured_only) query = query.eq("featured", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z4 } from "npm:zod@^4.6.5";
var list_blog_posts_default = defineTool4({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List blog and insight articles with their title, slug, category, publish state and publish date.",
  inputSchema: {
    search: z4.string().nullable().describe("Optional text to match against the post title."),
    publish_state: z4.string().nullable().describe("Optional publish state filter: draft, scheduled, published, archived or review."),
    limit: z4.number().int().nullable().describe("Maximum number of posts to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, publish_state, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("blog_posts").select(
      "id, title, slug, category, sector, content_type, summary, publish_state, published_at, read_time_minutes"
    ).order("published_at", { ascending: false, nullsFirst: false }).limit(take);
    if (search) query = query.ilike("title", `%${search}%`);
    if (publish_state) {
      query = query.eq(
        "publish_state",
        publish_state
      );
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-rfp-submissions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z5 } from "npm:zod@^4.6.5";
var list_rfp_submissions_default = defineTool5({
  name: "list_rfp_submissions",
  title: "List RFP submissions",
  description: "List tender and RFP submissions received through the website. Only returns rows the signed-in account is allowed to read.",
  inputSchema: {
    status: z5.string().nullable().describe("Optional status filter, for example 'new'."),
    limit: z5.number().int().nullable().describe("Maximum number of submissions to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("rfp_submissions").select(
      "id, project_name, company_name, contact_name, email, phone, project_type, project_location, estimated_value_range, estimated_timeline, status, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.2.0";
import { z as z6 } from "npm:zod@^4.6.5";
var list_contact_submissions_default = defineTool6({
  name: "list_contact_submissions",
  title: "List contact enquiries",
  description: "List contact-form enquiries received through the website. Only returns rows the signed-in account is allowed to read.",
  inputSchema: {
    status: z6.string().nullable().describe("Optional status filter, for example 'new'."),
    limit: z6.number().int().nullable().describe("Maximum number of enquiries to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("contact_submissions").select(
      "id, name, company, email, phone, submission_type, service_origin, message, status, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { enquiries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dinliarttwuzzozyvuiu";
var mcp_default = defineMcp({
  name: "ascentgroupwebsitev1-47",
  title: "AscentGroupWebsiteV1 (47)",
  version: "0.1.0",
  instructions: "Tools for the Ascent Group Construction website. Read projects, services and articles, and review RFP and contact enquiries received through the site. Every tool acts as the signed-in account, so results respect that account's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_services_default,
    list_blog_posts_default,
    list_rfp_submissions_default,
    list_contact_submissions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.2.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
